### ISSUE TITLE
Execution in non-interactive environment

### ISSUE THREAD

**Issue by lymperis-e** [opengeos/segment-geospatial#10]
I am trying to make ```samgeo``` to work outside the context of a python notebook. I already subclassed SamGeo and overrided the tiff_to_tiff method to remove the ```tqdm``` wrapper from the ```sample_grid``` iterator. Even still, the process gets frozen and am still unable to properly debug the issue. Are there any other jupyter-specific methods/classes used?

(I am developing a QGIS wrapper [here](https://github.com/lymperis-e/qgis-segment-anything) )

**Comment by vidlb** [comment]
Hi @lymperis-e , I think your problem is relative to QGIS and how you call the pytorch in the background, not segment-geospatial. It can be problem when the GPU is used by a QGIS thread and you try to init a pytorch model.  

To avoid freeze and errors in one of my script, I had to add this code to the class definition :  

```py
class Process(QgsProcessingAlgorithm):
    ....
    def flags(self):
        return super().flags() | QgsProcessingAlgorithm.FlagNoThreading
```

Not sure if this the same logic in plugins...
But I'm pretty sure this is a threading problem, which is common when coding PyQt.  

Hope this will help.

**Comment by giswqs** [comment]
@vidlb Thank you for helping out. Closing this issue for now. Feel free to reopen it if you are still experiencing issues @lymperis-e

**Comment by sharoseali** [comment]
HI.
I am working with Fast Sam and want to execute Fast Sam without a notebook, like a simple Python script. I want to save the final output image in a directory. But `show_anns()` function is giving a `Segmentation fault (core dumped)` error. By debugging more , the function 
```
fast_show_mask_gpu(
                annotations,
                plt.gca(),
                random_color=mask_random_color,
                bboxes=bboxes,
                points=points,
                pointlabel=point_label,
                retinamask=retina,
                target_height=original_h,
                target_width=original_w,
            )
```
is creating the problem.  Should I make edits  in `fast_show_mask_gpu` or is there any  easy approach to bypassing this function and save the final image with colorful masks like below. Thanks.

![mask](https://github.com/opengeos/segment-geospatial/assets/19869426/ba03b445-ff9e-4896-bd02-88fc6e72c3c9)

**Comment by giswqs** [comment]
Feel free to submit a pull request if you can fix the issue
