### ISSUE TITLE
'SamGeo' object has no attribute 'mask_generator

### ISSUE THREAD

**Issue by dipesh-chatrola** [opengeos/segment-geospatial#100]
**Although in samgeo.py file it's available but I am getting this error.**

Traceback (most recent call last):
lib\site-packages\samgeo\samgeo.py", line 207, in generate
mask_generator = self.mask_generator  # The automatic mask generator
AttributeError: 'SamGeo' object has no attribute 'mask_generator'

**Comment by dipesh-chatrola** [comment]
.

**Comment by LaurentBerder** [comment]
Hey, sorry I got the same issue in version `0.10.2`
`sam.generate(image, output="masks.tif", foreground=True, unique=True)`
```python
Traceback (most recent call last):
  File "interactiveshell.py", line 3553, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-21-625ba53ba81a>", line 1, in <module>
    sam.generate(image, output="masks.tif", foreground=True, unique=True)
  File "Lib\site-packages\samgeo\samgeo.py", line 208, in generate
    mask_generator = self.mask_generator  # The automatic mask generator
                     ^^^^^^^^^^^^^^^^^^^
AttributeError: 'SamGeo' object has no attribute 'mask_generator'
```

What was the remediation for this?

**Comment by LaurentBerder** [comment]
> When you initialize the `SamGeo` object, you need to set `automatic=True`
> 
> ```
> sam = SamGeo(
>     model_type="vit_h",
>     automatic=True,
>     sam_kwargs=None,
> )
> ```
> 
> Otherwise no `mask_generator` attribute will be set. Per:
> 
> [segment-geospatial/samgeo/samgeo.py](https://github.com/opengeos/segment-geospatial/blob/9b55c6a5e7eb0e51416af3b1e13953bb740aad66/samgeo/samgeo.py#L99-L101)
> 
> Lines 99 to 101 in [9b55c6a](/opengeos/segment-geospatial/commit/9b55c6a5e7eb0e51416af3b1e13953bb740aad66)
> 
>  if automatic: 
>      # Segment the entire image using the automatic mask generator 
>      self.mask_generator = SamAutomaticMaskGenerator(self.sam, **sam_kwargs)

Wouldn't it make sense then, if it's mandatory, to add `automatic=True` as a default ?
