### ISSUE TITLE
Add support for box prompts

### ISSUE THREAD

**Issue by elaliberte** [opengeos/segment-geospatial#113]
I've tried point prompts and this works well - thanks!
However, I can't see if box prompts are supported and if so, how. If they're supported it would be great to add it in the documentation.

**Comment by giswqs** [comment]
Box prompts are the same as the original SAM in the format of `[xmin, ymin, xmax, ymax]`. See this example.

https://github.com/facebookresearch/segment-anything/blob/main/notebooks/predictor_example.ipynb

**Comment by elaliberte** [comment]
Thank you. However, I can't get it to work. Would it please be possible to add an example of how to use box prompts in this example? https://samgeo.gishub.org/examples/input_prompts/

**Comment by giswqs** [comment]
Sorry for the delay. I finaly have time to work on this. SAM does support multiple input boxes. See https://github.com/facebookresearch/segment-anything/issues/381#issuecomment-1573355439

I will make it easier to use input boxes in samgeo by accepting geographic coordinates in addition to xy.
