### ISSUE TITLE
Interactive segmentation with input prompts [Win error 32]

### ISSUE THREAD

**Issue by oscarbau** [opengeos/segment-geospatial#121]
### Environment Information

-   samgeo version: 0.8.2
-   Python version: 3.9.16
-   Operating System: Windows 10

### Description

Describe what you were trying to get done.
Tell us what happened, what went wrong, and what you expected to happen.

When doing Interactive segmentation with input prompts, I get the first segmentation done, but when I try to reset and give different foreground and background points I get the following error:

[WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\XXX\\AppData\\Local\\Temp\\masks_slcdye.tif'

![image](https://github.com/opengeos/segment-geospatial/assets/41731874/3c53606d-fa4b-43ef-ba32-a5c258110170)

**Comment by giswqs** [comment]
Thank you for reporting. Run the following and restart the kernel. 

```python
import samgeo
samgeo.update_package()
```
