### ISSUE TITLE
Return image coordinates of center of segmentation boxes

### ISSUE THREAD

**Issue by lukesteinbicker** [opengeos/segment-geospatial#128]
### Description

Adds a new argument, return_coords, to predict function in text_sam.py. If True, the function returns a list of tuples containing the pixel coordinates of each mask

### Source code

```
return_coords=False #place along with arguments for predict function

if return_coords: #place inside predict function body
            boxlist = []
            for box in self.boxes:
                box = box.cpu().numpy()
                boxlist.append((box[0], box[1]))
            return boxlist
```

**Comment by giswqs** [comment]
Good suggestion. Would you like to submit a pull request to add it?

**Comment by lukesteinbicker** [comment]
Just submitted it. Let me know if there are any issues.
