### ISSUE TITLE
ImportError: libGL.so.1: cannot open shared object file when attempting to import samgeo in docker container

### ISSUE THREAD

**Issue by jsolly** [opengeos/segment-geospatial#138]
## Environment Information

-   samgeo version: 0.8.4
-   Python version: 3.11
-   Operating System: Ubuntu (Docker)

## Steps to Reproduce
I have the following Dockerfile
```dockerfile
FROM continuumio/miniconda3

RUN apt-get update -y
RUN conda update -y conda
RUN conda install -c conda-forge segment-geospatial -y

CMD ["python3", "do_things.py"]
```
Python file
```py
# do_things.py
from samgeo import SamGeo
```
When `do_things.py` attempts to import samgeo,  I get an error:

```shell
Traceback (most recent call last):
  File "/project/step4_segment_granules.py", line 2, in <module>
    from samgeo import SamGeo
  File "/opt/conda/lib/python3.10/site-packages/samgeo/__init__.py", line 8, in <module>
    from .samgeo import *
  File "/opt/conda/lib/python3.10/site-packages/samgeo/samgeo.py", line 6, in <module>
    import cv2
ImportError: libGL.so.1: cannot open shared object file: No such file or directory
```

## Workaround
After adding this line, the error goes away, and everything works as expected
```
RUN apt-get install libgl1-mesa-glx -y
```

## Thoughts
There are a couple of issues mentioning import errors, but none of the errors are this specific one.
https://github.com/opengeos/segment-geospatial/issues/53
https://github.com/opengeos/segment-geospatial/issues/76

**Comment by giswqs** [comment]
The `mesa-libGL` package is included in the conda-forge recipe. It should install that automatically. Not sure why it does work in your case.
https://github.com/giswqs/segment-geospatial-feedstock/blob/main/recipe/yum_requirements.txt

The samgeo Dockerfile seems working fine
https://github.com/opengeos/segment-geospatial/blob/main/Dockerfile

**Comment by jsolly** [comment]
Can someone confirm that the Dockerfile mentioned in the issue description also fails for them?

If it works for someone else, I am happy to close this issue.

**Comment by giswqs** [comment]
I misspoke. The `libgl1` needs to be installed on Linux for samgeo to work. The conda-forge package does not comes with `libgl1`.  

https://github.com/opengeos/segment-geospatial/blob/main/Dockerfile#L21
```bash
RUN apt update; apt install -y libgl1
```

**Comment by jsolly** [comment]
Okay, then I suggest adding that line to the documentation for installing from conda forge.

Here is [a PR that does that](https://github.com/opengeos/segment-geospatial/pull/141).
