### ISSUE TITLE
Creating coordinates for the objects that detected 

### ISSUE THREAD

**Issue by next-drought** [opengeos/segment-geospatial#145]
### Description

Can we generate coordinates for the objects that are segmented from the image? In that way, the objects can have more spatial features which can be better for other model training purposes such as autopilot system training.

**Comment by giswqs** [comment]
This is already supported. You can convert the segmentation raster to vector with the `raster_to_vector()` function. 
https://samgeo.gishub.org/common/#samgeo.common.raster_to_vector
