### ISSUE TITLE
Use dedicated GPU of laptop

### ISSUE THREAD

**Issue by ravishbapna** [opengeos/segment-geospatial#154]
My office laptop has dedicated GPU. Instead of using Google Colab, it would be great if segment-geospatial package has the functionality of using laptop GPU through jupyter lab or jupyter notebook. Thank you in advance.

**Comment by giswqs** [comment]
Yes, it already supports GPU. Install the package using mamba. It should automatically install the pytorch-gpu version. 

```python
conda create -n geo python=3.10
conda activate geo
conda install -c conda-forge mamba
mamba install -c conda-forge segment-geospatial
```

**Comment by ravishbapna** [comment]
Thank you for your response. I tried your suggested procedure but it does not install pytorch-gpu. When I try to install pytorch-gpu using mamba install -c conda-forge pytorch-gpu, an error is popping as shown in screenshot. Kindly help.
![Screenshot 2023-08-05 225056](https://github.com/opengeos/segment-geospatial/assets/111732501/e72f1652-3c15-4922-8ac7-377a56c99886)
