### ISSUE TITLE
Add support for FastSam

### ISSUE THREAD

**Issue by giswqs** [opengeos/segment-geospatial#158]
### Discussed in https://github.com/opengeos/segment-geospatial/discussions/156

<div type='discussions-op-text'>

<sup>Originally posted by **torrinworx** August  2, 2023</sup>
I'm trying to understand the scope of what Sam models work with the package, would I be able to use the [FastSam](https://github.com/CASIA-IVA-Lab/FastSAM#model-checkpoints) models (or other segmentation models) with segment-geospatial?</div>

References:
- https://colab.research.google.com/github/roboflow-ai/notebooks/blob/main/notebooks/how-to-segment-anything-with-fast-sam.ipynb
- https://youtu.be/yHNPyqazYYU

**Comment by thipokKub** [comment]
[Light SAM-HQ](https://github.com/SysCV/sam-hq) would be nice too

**Comment by skylning** [comment]
Looking forward to add support for FastSAM

**Comment by giswqs** [comment]
HQ-SAM support has been added in https://github.com/opengeos/segment-geospatial/pull/161. Looking into FastSAM now.

**Comment by giswqs** [comment]
I have added FastSAM to PyPI. Install it with `pip install segment-anything-fast`
https://github.com/opengeos/FastSAM

Hope it will be available on conda-forge soon. 
https://github.com/conda-forge/staged-recipes/pull/23682
