### ISSUE TITLE
ADDING LABELS ON DETECTED OBJECTS

### ISSUE THREAD

**Issue by laktebomar** [opengeos/segment-geospatial#16]
### Description

As I know SAM can tell you what objects are on the image so it will be good to add labels on the detected objects. it will make life much easier.

another thing is, is it possible to make this as a rest api?

**Comment by giswqs** [comment]
SAM only does the segmentation. Users need to add labels/annotations manually. See https://github.com/opengeos/segment-geospatial/issues/5 

Developing a Rest API is beyond my expertise. You are welcome to contribute to the project if you are familiar with Rest API.
