### ISSUE TITLE
[JOSS review] Contribution & Tests

### ISSUE THREAD

**Issue by SimonMolinsky** [opengeos/segment-geospatial#166]
#### Refers to

`Community guidelines: Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support`

and

`Automated tests: Are there automated tests or manual steps described so that the functionality of the software can be verified?`

#### Issues

Issue 1:

The file `contributing.md` is in the directory `docs` and compiled with the package documentation. Usually, packages have this file in a top-level directory, but if it is not desirable, **please add a link in `README.md` to the contribution guidelines**.

Issue 2:

Here: https://github.com/opengeos/segment-geospatial/blob/536172826ff89963901a537c6d0343bef4f34894/docs/contributing.md?plain=1#L103 you mention `README.rst` file where new functions should be linked. Where is this file? Do you know if this is a typo?

Issue 3:

Here: https://github.com/opengeos/segment-geospatial/blob/536172826ff89963901a537c6d0343bef4f34894/docs/contributing.md?plain=1#L102 you write about tests, but there is no explanation how those tests should be performed? What contributor should do to run tests in a local environment?

Issue 4

You have three types of requirements*.txt files in your top-level directory. Should contributors care about the files that end with `dev.txt` or `docs.txt`?

**Comment by giswqs** [comment]
@SimonMolinsky Thank you for your feedback. These issues have been resolved in #169. 

1. Mkdocs can't access files outside the `docs` to build the documentation. Therefore, `contributing.md` is placed within the `docs` directory. I have added a link in `README.md` to refer to `contributing.md`.
2. The typo has been corrected. `README.rst` -> `README.md`
3. Added the `Unit testing` section in `contributing.md`
4. Added the `Add new dependencies` section in `contributing.md`
