### ISSUE TITLE
Dockerfile

### ISSUE THREAD

**Issue by austinmw** [opengeos/segment-geospatial#17]
### Description

Since this project requires GDAL so the requirements are fairly complex to install, it would be very helpful to include a Dockerfile

**Comment by giswqs** [comment]
It uses the pre-trained model as it is. No fine-tuning yet.

**Comment by giswqs** [comment]
Yes, that would be a great feature to add. I will see you if I can implement it. Contributions are always welcome.

**Comment by swdmike** [comment]
Yes, a dockerfile is really necessary. Thanks.

**Comment by p-vdp** [comment]
I can confirm the installation steps necessary to run the example Jupyter notebooks aren't very clear. A dockerfile of your demo environment would be very appreciated! Or at least add detail to the instructions on how you set it up from one of the docker-stacks.

In my case I have your example notebooks running in [jupyter/datascience-notebook](https://hub.docker.com/r/jupyter/datascience-notebook/) after installing segment-geospatial with mamba. However the TIF format rasters don't appear as layers in the leafmaps. I'm sure I'm missing a dependency but I don't know what it is.

**Comment by giswqs** [comment]
@p-vdp The file extension problem has been fixed in https://github.com/opengeos/segment-geospatial/pull/43. Try changing the file extension from `.tiff` to `.tif`. 

Do you have a Dockerfile that you can share?

**Comment by p-vdp** [comment]
Amazingly quick response and fix! Thank you!!
