### ISSUE TITLE
Support for mps (Apple GPU) in samGeo Options

### ISSUE THREAD

**Issue by nickoutram** [opengeos/segment-geospatial#177]
Hey my understanding is that PyTorch now supports using MPS device (using `torch.device("mps")`), would it be possible to be able to have this option in the initialisation of the samGeo class?

**Comment by giswqs** [comment]
Unfortunately, segment-anything does not seem to support MPS device yet. See https://github.com/facebookresearch/segment-anything/issues/453

There is not much samgeo can do until SAM supports it natively. Will revisit this issue when it becomes possible.

**Comment by nickoutram** [comment]
Thanks @giswqs, according to the linked thread the previous problem should now be fixed by nightly PyTorch builds. Is there any possibility of having the ability to pass this argument through to SAM/PyTorch even though it may not be supported by an official release just yet?

**Comment by giswqs** [comment]
The `device` argument is already in the `SamGeo` constructor. You can pass `device='mps'` if the SAM supports it. 
https://github.com/opengeos/segment-geospatial/blob/main/samgeo/samgeo.py#L69

**Comment by nickoutram** [comment]
Much appreciated - seems to be working
