### ISSUE TITLE
install gdal and rasterio dependencies on Windows

### ISSUE THREAD

**Issue by pgfernandez** [opengeos/segment-geospatial#18]
It looks like the best way to install gdal and rasterio dependencies on windows is through pipwin. With pip is really challenging

**Comment by giswqs** [comment]
It is recommended to use conda to install segment-geospatial and its dependencies.

https://samgeo.gishub.org/installation/#install-from-conda-forge
```python
conda install -n base mamba -c conda-forge
mamba create -n geo segment-geospatial python -c conda-forge
```
