### ISSUE TITLE
Google maps needs API key (Interactive maps section)

### ISSUE THREAD

**Issue by TimeScience** [opengeos/segment-geospatial#187]
Section 7 now needs google API key before map will load

```
m_leafmap.set_api_key('your_google_api_key')
m = leafmap.Map(center=[-35.287243572265822, 149.109864881177202], zoom=19)
m.add_basemap("SATELLITE")
```

**Comment by giswqs** [comment]
I recently removed Google basemaps from leafmap to avoid vialoting Google Maps' [terms of service](https://cloud.google.com/maps-platform/terms). I need to update the notebook examples to replace Google Earth basemaps with other alternatives. 
https://github.com/opengeos/leafmap/pull/522
