### ISSUE TITLE
Missing dependency: Downloaded tif will not display without ipyleaflet being installed

### ISSUE THREAD

**Issue by TimeScience** [opengeos/segment-geospatial#188]
Section 20 needs a

`!pip install ipyleaflet`

**Comment by giswqs** [comment]
Which notebook are your referring to? I don't know where Sectioin 20 is.

**Comment by giswqs** [comment]
samgeo already includes leafmap as a dependency, which builds on ipyleaflet, so ipyleaflet should not need to be installed separately.

**Comment by TimeScience** [comment]
Sorry that wasn't more clear.

In the "SAM-Geospatial-satellite.ipynb" notebook, the section below won't run unless one installs ipyleaflet.
If I pip install ipyleaflet before this section, then everything runs fine.

See error below.

```
m.layers[-1].visible = False  # turn off the basemap
m.add_raster(image, layer_name="Image")
m

```
![image](https://github.com/opengeos/segment-geospatial/assets/3067588/1f01a147-6498-4a90-824c-d3b24cdba1fe)

**Comment by giswqs** [comment]
Try restarting runtime after installing samgeo. It already includes ipyleaflet and localtileserver. There is no need to install them separately. I just tested it on Colab. It works as expected. 

```python
%pip install segment-geospatial
```

![image](https://github.com/opengeos/segment-geospatial/assets/5016453/17cf1c19-98ca-44fc-8506-0f4329e91180)
