### ISSUE TITLE
Optmization

### ISSUE THREAD

**Issue by fvcamargo** [opengeos/segment-geospatial#19]
Please add script models for fine tunning
like:

optimizer = torch.optim.Adam(sam_model.mask_decoder.parameters()) 
loss_fn = torch.nn.MSELoss()
with torch.no_grad():
	image_embedding = sam_model.image_encoder(input_image)

low_res_masks, iou_predictions = sam_model.mask_decoder(
  image_embeddings=image_embedding,
  image_pe=sam_model.prompt_encoder.get_dense_pe(),
  sparse_prompt_embeddings=sparse_embeddings,
  dense_prompt_embeddings=dense_embeddings,
  multimask_output=False,
)

**Comment by giswqs** [comment]
Can you provide the complete source for a working example?

**Comment by giswqs** [comment]
Closing to due to no response.
