### ISSUE TITLE
map not displaying

### ISSUE THREAD

**Issue by sanjivjha** [opengeos/segment-geospatial#199]
m = leafmap.Map(center=[34.040984, -118.491668], zoom=19, height="600px")
m.add_basemap("SATELLITE")
m

causing this error
[Open Browser Console for more detailed log - Double click to close this message]
Failed to load model class 'LeafletMapModel' from module 'jupyter-leaflet'
makeError@http://localhost:8889/static/components/requirejs/require.js:168:26
onScriptError@http://localhost:8889/static/components/requirejs/require.js:1735:45

**Comment by giswqs** [comment]
Make sure you follow the instructions [here](https://samgeo.gishub.org/installation/#install-from-conda-forge) to install the package. 

```python
conda create -n geo python
conda activate geo
conda install -c conda-forge mamba
mamba install -c conda-forge segment-geospatial
```
