### ISSUE TITLE
UAV dataset

### ISSUE THREAD

**Issue by fvcamargo** [opengeos/segment-geospatial#20]
I am using it for UAV RGB and multispectral dataset.

Works fine with RGB but multispectral do not work, please provide some script ideas to use UAV orthomosaics (.tif)

**Comment by felipenorconsult** [comment]
I have used RGB (aerial image as geotiff) with sound results

**Comment by giswqs** [comment]
I believe SAM only supports RGB images. segment-geospatial is only a wrapper of SAM. 
https://github.com/facebookresearch/segment-anything
