### ISSUE TITLE
ValueError: Given nodata value, nan, is beyond the valid range of its data type, uint8.

### ISSUE THREAD

**Issue by sm-potter** [opengeos/segment-geospatial#202]
I have a single band .tif file which is in floating point and no NaN values present.  However when I run the following on my image:
```

mask = "segment.tif"
sam.generate(
    image, mask, batch=True, foreground=True, erosion_kernel=(3, 3), mask_multiplier=255
)
```

It returns:

```
rasterio/_io.pyx in rasterio._io.DatasetWriterBase.__init__()

ValueError: Given nodata value, nan, is beyond the valid range of its data type, uint8.

```

But I already filled any NaN values with -999, so I am confused why rasterio is complaining?

**Comment by giswqs** [comment]
The value range of uint is 0-255. No negative value is allowed
