### ISSUE TITLE
model installed from conda-forge not using GPU

### ISSUE THREAD

**Issue by wb8267** [opengeos/segment-geospatial#203]
Hi. I've installed samgeo in a fresh win10 anaconda environment with only python3.11 installed, I followed the instructions:
https://github.com/opengeos/segment-geospatial#install-from-conda-forge

However, I found that torch.cuda.is_available() returns false.  Is there a step I should be taking to enable it to use the GPU instead?

**Comment by giswqs** [comment]
Make sure you install the CUDA tools for Windows. See https://docs.nvidia.com/cuda/cuda-installation-guide-microsoft-windows/index.html
