### ISSUE TITLE
localtileserver issue 

### ISSUE THREAD

**Issue by Saroramath** [opengeos/segment-geospatial#206]
### Environment Information

-   samgeo version: Default (Downloading segment_geospatial-0.10.1-py2.py3-none-any.whl )
-   Python version: 3.10.12
-   Operating System: Google Colab

### Description

Error running the tutorial Satellite
### What I Did
I was running the Satellite tutorial and it is giving error on this code cell: 
m.add_raster(image, layer_name="Image")
```

ImportError: localtileserver is not installed. Please install it before proceeding. https://github.com/banesullivan/localtileserver

```
trying pip install localtileserver does not resolve.

**Comment by giswqs** [comment]
Did you following the intructions to install localtileserver?
```
pip install localtileserver
```

**Comment by Saroramath** [comment]
Yes, I had tried
```
pip install localtileserver
```
but it did not help with the error.

**Comment by giswqs** [comment]
It is likely you have a gdal installation problem. Run the following. If it does not work, then it is a gdal problem. 

```python
from osgeo import gdal
```

**Comment by Saroramath** [comment]
Thank, this command is running fine but the error is still there.
I did have issues with osgeo in my local environment but currently I am running "satellite.ipynb" in Google Colab.

**Comment by giswqs** [comment]
It works fine on my end. Make sure you restart runtime after installation. 
![image](https://github.com/opengeos/segment-geospatial/assets/5016453/bb6a2e55-bf55-453f-b3bc-95b1e41ab2e2)

**Comment by Saroramath** [comment]
Thanks, It's running for me as well. Just the error on this code cell still persist. Please close the issue if fine.
<img width="1463" alt="Screenshot 2023-11-01 at 1 02 06 PM" src="https://github.com/opengeos/segment-geospatial/assets/67832595/9f9bfde8-b4a6-4345-bac3-17d936b3ff0f">
<img width="1463" alt="Screenshot 2023-11-01 at 1 01 16 PM" src="https://github.com/opengeos/segment-geospatial/assets/67832595/766aa781-0070-46e9-a61f-f9715f2db602">

**Comment by fnavarro620** [comment]
Recently I solved this issue installing localtileserver on this version  `pip install localtileserver == 0.3.5`

**Comment by Saroramath** [comment]
Thanks, 
``pip install localtileserver==0.3.5``
does resolves the issue.

**Comment by giswqs** [comment]
I tested the latest localtileserver on Colab. If you restart the runtime after installation, everything works fine.
