### ISSUE TITLE
failed in activating conda environment

### ISSUE THREAD

**Issue by fitrialya** [opengeos/segment-geospatial#208]
Hello, i would like to ask for a solution for the issue i faced during activate the conda environment in ArcGISPro. i have completed to create the conda env, and failed on the next step to activate the env. the issues code appear like this:

CommandNotFoundError: Your shell has not been properly configured to use 'conda activate'.
If using 'conda activate' from a batch script, change your
invocation to 'CALL conda.bat activate'.

To initialize your shell, run
  $ conda init <SHELL_NAME>

Currently supported shells are:
  - bash
  - cmd.exe
  - fish
  - tcsh
  - xonsh
  - zsh
  - powershell

See 'conda init --help' for more information and options.

IMPORTANT: You may need to close and restart your shell after running 'conda init'.

Please do inform if there any step i skipped or i need to install any other thing. Thank you

**Comment by giswqs** [comment]
How did you create the conda env? You should use the ArcGIS command prompt to create a new conda env rather than using new conda installation

**Comment by fitrialya** [comment]
ah, sorry. I solved the activated step. but when i check on ArcgisPro, the environment are stated broken, and cannot be activated.
![image](https://github.com/opengeos/segment-geospatial/assets/128754326/4e9f5c19-fd9c-463c-b861-f764ee0dbb2c)

eventough in command prompt already activated

**Comment by giswqs** [comment]
I just created a new video tutorials on how to install samgeo in ArcGIS Pro 3.2
🎥 Video: https://youtu.be/HXunNWAccYw
📚 Notebook: https://samgeo.gishub.org/examples/arcgis
