### ISSUE TITLE
cuda_installation_issue

### ISSUE THREAD

**Issue by MrZombie69232** [opengeos/segment-geospatial#21]
### Environment Information

-   samgeo version: 0.3.0
-   Python version: 3.9
-   Operating System: windows 11

### Description

I checked fo the cuda installation but still it's not being detected .

### What I Did

```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
```

**Comment by giswqs** [comment]
The cuda detection relies on pytorch. Run the following script. If it returns False, then your pytorch is not installed properly. It is a pytorch installation issue rather than a segment-geospatial issue. 

```python
import torch
print(torch.cuda.is_available())
```

**Comment by MrZombie69232** [comment]
I did pytorch reinstallation but still the same issue exists . I will do with fresh environment and will check again .

Thank you very much !

**Comment by giswqs** [comment]
Run `conda list` and make sure that `pytorch-gpu` is on the list. 

![image](https://user-images.githubusercontent.com/5016453/235802006-4901fc36-e981-4389-9883-e595b50afd15.png)
