### ISSUE TITLE
installing dependencies error

### ISSUE THREAD

**Issue by hannahkfriedrich** [opengeos/segment-geospatial#211]
### Environment Information

-   samgeo version: 
-   Python version: 3
-   Operating System: colab

### Description
I tried to run the maxar_open_data.ipynb in colab following the example. 

When I tried to install segment-geospatial, I encoutered the following error: 

Installing collected packages: aniso8601, whitebox, werkzeug, snuggs, safetensors, pyrsistent, palettable, jedi, h11, geojson, cachelib, affine, uvicorn, rasterio, pystac, large-image, jsonschema, huggingface-hub, server-thread, large-image-source-rasterio, flask-restx, flask-cors, Flask-Caching, timm, segment-anything-py, segment-anything-hq, pystac-client, localtileserver, whiteboxgui, leafmap, segment-geospatial
  Attempting uninstall: werkzeug
    Found existing installation: Werkzeug 3.0.1
    Uninstalling Werkzeug-3.0.1:
      Successfully uninstalled Werkzeug-3.0.1
  Attempting uninstall: jsonschema
    Found existing installation: jsonschema 4.19.2
    Uninstalling jsonschema-4.19.2:
      Successfully uninstalled jsonschema-4.19.2
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
lida 0.0.10 requires fastapi, which is not installed.
lida 0.0.10 requires kaleido, which is not installed.
lida 0.0.10 requires python-multipart, which is not installed.
Successfully installed Flask-Caching-2.1.0 affine-2.4.0 aniso8601-9.0.1 cachelib-0.9.0 flask-cors-4.0.0 flask-restx-1.2.0 geojson-3.1.0 h11-0.14.0 huggingface-hub-0.19.0 jedi-0.19.1 jsonschema-4.17.3 large-image-1.26.0 large-image-source-rasterio-1.26.0 leafmap-0.28.1 localtileserver-0.7.2 palettable-3.3.3 pyrsistent-0.20.0 pystac-1.8.3 pystac-client-0.7.5 rasterio-1.3.9 safetensors-0.4.0 segment-anything-hq-0.3 segment-anything-py-1.0 segment-geospatial-0.10.2 server-thread-0.2.0 snuggs-1.4.7 timm-0.9.10 uvicorn-0.24.0.post1 werkzeug-2.3.8 whitebox-2.3.1 whiteboxgui-2.3.0

This led to issues a couple of lines later when I tried to add the image to the map 

ContextualVersionConflict                 Traceback (most recent call last)
[/usr/local/lib/python3.10/dist-packages/leafmap/common.py](https://localhost:8080/#) in check_package(name, URL)
    159     try:
--> 160         __import__(name.lower())
    161     except Exception:

10 frames
ContextualVersionConflict: (werkzeug 3.0.1 (/usr/local/lib/python3.10/dist-packages), Requirement.parse('werkzeug!=2.0.0,<3.0.0'), {'flask-restx'})

During handling of the above exception, another exception occurred:

ImportError                               Traceback (most recent call last)
[/usr/local/lib/python3.10/dist-packages/leafmap/common.py](https://localhost:8080/#) in check_package(name, URL)
    160         __import__(name.lower())
    161     except Exception:
--> 162         raise ImportError(
    163             f"{name} is not installed. Please install it before proceeding. {URL}"
    164         )

ImportError: localtileserver is not installed. Please install it before proceeding. https://github.com/banesullivan/localtileserver

Even after manually installing localtileserver with pip, I'm still encountering issues. Seems like an issue with version of werkzeug and other packages? Thanks!

**Comment by giswqs** [comment]
Did you restart the kernel after installation?

**Comment by hannahkfriedrich** [comment]
Ahh, thanks!
