### ISSUE TITLE
Add_vector is not working always, segment geopackage is not loading onto the map

### ISSUE THREAD

**Issue by MuFazil** [opengeos/segment-geospatial#221]
## Environment Information
leafmap version: 0.29.4

Python version:

Operating System: Colab

## Description
I created the segment.tif file and used this code to add the layer to basemap :
style = {
"color": "#3388ff",
"weight": 2,
"fillColor": "#7c4185",
"fillOpacity": 0.5,
}
m.add_basemap("SATELLITE")

m.add_vector(vector, layer_name="Vector", style=style)
m

But the output is not as expected
![Screenshot 2023-11-29 223329](https://github.com/opengeos/segment-geospatial/assets/97659961/8982987a-46c5-421f-b650-3b868500d369)

The segmentation is fine since I tried plotting the segmented image as jpeg. The issue is with the add_vector function it seems.

**Comment by giswqs** [comment]
Please share the vector dataset that can reproduce the issue.
