### ISSUE TITLE
samgeo fails to load in conda/mamba environment

### ISSUE THREAD

**Issue by arthurgailes** [opengeos/segment-geospatial#230]
### Environment Information

-   samgeo version: 0.10.2
-   Python version: 3.9.18
-   Operating System: Windows 10

### Description

samgeo fails to load

### What I Did

```
mamba create -n samgeo
conda activate samgeo
mamba install segment-geospatial
```

May be related to https://github.com/opengeos/segment-geospatial/issues/76, but installing python 3.9 did not fix the issue.

ImportError                               Traceback (most recent call last)
Cell In[1], line 3
      1 import os
      2 # import leafmap
----> 3 from samgeo import SamGeo, tms_to_geotiff, get_basemaps

File [mypath]\Miniforge3\envs\samgeo\lib\site-packages\samgeo\__init__.py:8
      4 __email__ = "giswqs@gmail.com"
      5 __version__ = '0.10.2'
----> 8 from .samgeo import *

File [mypath]\Miniforge3\envs\samgeo\lib\site-packages\samgeo\samgeo.py:11
      8 import numpy as np
      9 from segment_anything import sam_model_registry, SamAutomaticMaskGenerator, SamPredictor
---> 11 from .common import *
     14 class SamGeo:
     15     """The main class for segmenting geospatial data with the Segment Anything Model (SAM). See
     16     https://github.com/facebookresearch/segment-anything for details.
     17     """

File [mypath]\Miniforge3\envs\samgeo\lib\site-packages\samgeo\common.py:13
     11 import shapely
     12 import pyproj
---> 13 import rasterio
...
---> 28 from rasterio._version import gdal_version, get_geos_version, get_proj_version
     29 from rasterio.crs import CRS
     30 from rasterio.drivers import driver_from_extension, is_blacklisted

ImportError: DLL load failed while importing _version: The specified procedure could not be found.

**Comment by giswqs** [comment]
It appears that rasterio was not installed properly on your computer. Please install it with the command below. 

```bash
mamba install -c conda-forge rasterio
```

**Comment by ishwar97** [comment]
Hello @giswqs, I created a fresh environment using conda and python=3.11.10 and installed segment-geospatial in it, when I try to import samgeo , it throws ImportError: DLL load failed while importing lib, flagging shapely as cause of error.

> from shapely.lib import GEOSException  # NOQA

Steps to reproduce 
`conda create -n geoenv
conda activate geoenv
conda install -c conda-forge segment-geospatial -y`

When I try to import shapely in conda env using python, it works. Its just that jupyter lab is not able to locate it. Can you suggest any work-around for this?
Thanks in advance!
