### ISSUE TITLE
self.save_masks unique value mask results are covered

### ISSUE THREAD

**Issue by liuhongyan123456** [opengeos/segment-geospatial#233]
When I run sam.generate(image, mask, foreground=True,erosion_kernel=(3, 3), unique=True) this code, I find that the previous mask result is overwritten by the subsequent mask result
![image](https://github.com/opengeos/segment-geospatial/assets/49739798/15ce92f5-4adb-4453-8924-c5b30c7a1354)
![image](https://github.com/opengeos/segment-geospatial/assets/49739798/30b090e7-4903-49de-a313-3117dd12299b)

**Comment by giswqs** [comment]
If you use the same output filename, it will overwrite. If you don't want to over the result, choose a different output filename. 

```python
sam.generate(image, "mask1.tif", foreground=True,erosion_kernel=(3, 3), unique=True) 
sam.generate(image, "mask2.tif", foreground=True,erosion_kernel=(3, 3), unique=True) 
```
