### ISSUE TITLE
Initialise FastSAM is not working

### ISSUE THREAD

**Issue by riokt** [opengeos/segment-geospatial#235]
### Environment Information

-   samgeo version: 0.10.2
-   Python version: 3.11
-   Operating System: Google Colab

### Description

why can't I initialize the FastSAM model?
![image](https://github.com/opengeos/segment-geospatial/assets/12220831/29b80f86-b4b7-4470-a770-ae05a5afa18a)

### What I Did

Change to this but not working
```
sam = SamGeo(model="FastSAM-x.pt", checkpoint_dir="content/FastSAM-x.pt")
```

**Comment by johngeoscrub** [comment]
Having the same issue in Google Collab for `vit_h`
```sam = SamGeo(
    model_type="vit_h",
    automatic=False,
    sam_kwargs=None,
)```

Yields Model checkpoint for `vit_h `not found.
```
Access denied with the following error:

 	Cannot retrieve the public link of the file. You may need to change
	the permission to 'Anyone with the link', or have had many accesses. 
```

I can indeed still access it from the browser however this seems to be new unexpected behavior - maybe its isolated to Google Collab?

**Comment by ihsan2805** [comment]
> [johngeoscrub](/johngeoscI

I have similar problem, the model from Samgeo.hq and FastSam , can not be downloaded automatically by system. And when i try to call the model (already downloaded in my laptop), it always failed. If you have solution, please share here. thank you

**Comment by grannycola** [comment]
Same problem

**Comment by johngeoscrub** [comment]
@ihsan2805 @grannycola this is not a complete fix but can maybe unblock you for the time being - do you still have issues if you import SamGeo like this `from samgeo import SamGeo` instead of `from samgeo.hq_sam import SamGeo` ?

**Comment by grannycola** [comment]
@johngeoscrub I used this:
```
from samgeo.fast_sam import SamGeo
sam = SamGeo(model="FastSAM-x.pt")
```

**Comment by ihsan2805** [comment]
@johngeoscrub yes, everything is normal when i use `from samgeo import SamGeo`

**Comment by giswqs** [comment]
If the automatic download fails, you can download the checkpoints manually and put them in the directory `~/.cache/torch/hub/checkpoints`. Alternatively, you can pass in the `checkpoint_dir` parameter pointing to your checkpoints directory when initializing `SamGeo`

-  FastSAM-x.pt:  https://drive.google.com/file/d/1m1sjY4ihXBU1fZXdQ-Xdj-mDltW-2Rqv/view?usp=sharing
- FastSAM-s.pt: https://drive.google.com/file/d/10XmSj6mmpmRb8NhXbtiuO9cTTBwR_9SV/view?usp=sharing
