### ISSUE TITLE
samgeo installation failed on arcggis pro 2.9

### ISSUE THREAD

**Issue by CHENG-WEI1128** [opengeos/segment-geospatial#237]
### Environment Information

-   samgeo version: latest version
-   Python version: 3.7.11 (from arcgis pro 2.9)
-   Operating System: Win10 and  arcgis pro 2.9

### Description

I try to install your geosam model on my arcgis pro by following your instruction on your segment-geospatial website, but the installation is failed and lots of modules aren't installed in new created geosam environment.

**The error message is below:**
(1)
warning  libmamba Extracted package cache 'C:\Users\2254\.conda\pkgs\backcall-0.2.0-pyhd3eb1b0_0' has invalid size
warning  libmamba Extracted package cache 'C:\Users\2254\.conda\pkgs\backcall-0.2.0-pyhd3eb1b0_0' has invalid SHA-256 checksum
Transaction

  Prefix: D:\Program Files\ArcGIS\Pro\bin\Python\envs\samgeo

  Updating specs:

   - arcpy
   - deep-learning-essentials
   - segment-geospatial
   - pygis
   - ca-certificates
   - certifi
   - openssl

(2)
| Uninstalling prior versions of arcgis widget
Installing D:\Program Files\ArcGIS\Pro\bin\Python\envs\samgeo\lib\site-packages\arcgis\widgets/js/dist -> arcgis
Up to date: D:\Program Files\ArcGIS\Pro\bin\Python\envs\samgeo\share\jupyter\nbextensions\arcgis\arcgis-map-ipywidget.jsUp to date: D:\Program Files\ArcGIS\Pro\bin\Python\envs\samgeo\share\jupyter\nbextensions\arcgis\arcgis-map-ipywidget.js.map
Up to date: D:\Program Files\ArcGIS\Pro\bin\Python\envs\samgeo\share\jupyter\nbextensions\arcgis\extension.js
- Validating: ok

    To initialize this nbextension in the browser every time the notebook (or other app) loads:

       jupyter nbextension enable arcgis --py --sys-prefix

Enabling notebook extension arcgis/extension...
      - Validating: ok

done
ERROR conda.core.link:_execute(945): An error occurred while installing package 'esri::arcpy-base-3.2-py39_49743'.
Rolling back transaction: done
'cp950' codec can't decode byte 0xe6 in position 271: illegal multibyte sequence
()

UnicodeDecodeError('cp950', b'Traceback (most recent call last):\r\n  File "<string>", line 1, in <module>\r\n  File "D:\\Program Files\\ArcGIS\\Pro\\bin\\Python\\envs\\samgeo\\lib\\site-packages\\arcpy_init.py", line 231, in install\r\n    from lxml import etree\r\nImportError: DLL load failed while importing etree: \xe6\x89\xbe\xe4\xb8\x8d\xe5\x88\xb0\xe6\x8c\x87\xe5\xae\x9a\xe7\x9a\x84\xe7\xa8\x8b\xe5\xba\x8f\xe3\x80\x82\r\n', 271, 272, 'illegal multibyte sequence')
()

**The installed modules list of new geosam environment is below:**

# Name                    Version                   Build  Channel
archspec                  0.2.1              pyhd3eb1b0_0
boltons                   23.0.0           py39haa95532_0
brotli-python             1.0.9            py39hd77b12b_7
bzip2                     1.0.8                he774522_0
ca-certificates           2023.12.12           haa95532_0
certifi                   2023.11.17       py39haa95532_0
cffi                      1.16.0           py39h2bbff1b_0
charset-normalizer        2.0.4              pyhd3eb1b0_0
colorama                  0.4.6            py39haa95532_0
conda                     23.11.0          py39haa95532_0
conda-libmamba-solver     23.12.0            pyhd3eb1b0_1
conda-package-handling    2.2.0            py39haa95532_0
conda-package-streaming   0.9.0            py39haa95532_0
cryptography              41.0.7           py39h89fc84f_0
distro                    1.8.0            py39haa95532_0
fmt                       10.1.1               h181d51b_1    conda-forge
idna                      3.4              py39haa95532_0
jsonpatch                 1.32               pyhd3eb1b0_0
jsonpointer               2.1                pyhd3eb1b0_0
libarchive                3.7.2                h313118b_1    conda-forge
libcurl                   8.5.0                h86230a5_0
libiconv                  1.17                 hcfcfb64_2    conda-forge
libmamba                  1.5.6                h3f09ed1_0    conda-forge
libmambapy                1.5.6            py39h2690a07_0    conda-forge
libsolv                   0.7.24               h23ce68f_0
libssh2                   1.10.0               he2ea4bf_2
libxml2                   2.12.4               hc3477c8_1    conda-forge
libzlib                   1.2.13               hcfcfb64_5    esri
lz4-c                     1.9.4                h2bbff1b_0
lzo                       2.10                 he774522_2
mamba                     1.5.6            py39hca8391b_0    conda-forge
menuinst                  2.0.1            py39hd77b12b_1
openssl                   3.2.0                hcfcfb64_1    conda-forge
packaging                 23.1             py39haa95532_0
pcre2                     10.42                h0ff8eda_0
pip                       23.3.1           py39haa95532_0
platformdirs              3.10.0           py39haa95532_0
pluggy                    1.0.0            py39haa95532_1
pybind11-abi              4                    hd3eb1b0_1
pycosat                   0.6.6            py39h2bbff1b_0
pycparser                 2.21               pyhd3eb1b0_0
pyopenssl                 23.2.0           py39haa95532_0
pysocks                   1.7.1            py39haa95532_0
python                    3.9.18                        0    esri
python_abi                3.9                      1_cp39    esri
reproc                    14.2.4               hd77b12b_1
reproc-cpp                14.2.4               hd77b12b_1
requests                  2.31.0           py39haa95532_0
ruamel.yaml               0.17.21          py39h2bbff1b_0
ruamel.yaml.clib          0.2.7            py39ha55989b_2    conda-forge
setuptools                68.2.2           py39haa95532_0
sqlite                    3.41.2               h2bbff1b_0
tqdm                      4.65.0           py39hd4e2768_0
ucrt                      10.0.20348.0         haa95532_0
urllib3                   1.26.18          py39haa95532_0
vc                        14.2                 h21ff451_1
vc14_runtime              14.38.33130         h82b7239_18    conda-forge
vs2015_runtime            14.38.33130         hcb4865c_18    conda-forge
wheel                     0.41.2           py39haa95532_0
win_inet_pton             1.1.0            py39haa95532_0
xz                        5.4.5                h8cc25b3_0
yaml-cpp                  0.8.0                hd77b12b_0
zlib                      1.2.13               hcfcfb64_5    conda-forge
zstandard                 0.19.0           py39h2bbff1b_0
zstd                      1.5.5                hd43e919_0

### What I Did
I haven't tred to adjust regedit.exe to deal with maxlength path issue due to my authority of current computer.
Is this failure related to maxlength path issue?

```

I want to know whether the failure of installation is because of my old version of arcgis pro? and how can I fix this?

Which version of arcgis pro is work for your geosam tool, 3.1, 3.2 or older version is acceptable?

Is there other version of samgeo  is suitable of older version of arcgis pro?

Many thanks!
```

**Comment by giswqs** [comment]
Please upgrade ArcGIS Pro to 3.x

**Comment by giswqs** [comment]
Upgrade ArcGIS Pro to 3.x and follow this [video tutorial](https://youtu.be/HXunNWAccYw) to install samgeo.
