### ISSUE TITLE
Problem with the Interactive segmentation using Points on Image

### ISSUE THREAD

**Issue by giswqs** [opengeos/segment-geospatial#238]
### Discussed in https://github.com/opengeos/segment-geospatial/discussions/234

<div type='discussions-op-text'>

<sup>Originally posted by **JoelDJ2002** January  8, 2024</sup>
I am facing a glitch in the Interactive segmentation using Points in image
<img width="365" alt="image" src="https://github.com/opengeos/segment-geospatial/assets/66190032/5abb8816-52fb-48c1-8ce4-89a258959fca">
When you select Foreground Point and then select Background points it automatically increments the number of background points. 
I restarted and reran the entire code 5 times. Apparantly I found out that it had choosen one points on its own outside the image somewhere randomly . 
It would be great if this issue could be resolved</div>

**Comment by giswqs** [comment]
I can't reproduce the issue. When placing markers outside the image, it should throw an error. 

![Peek 2024-01-18 00-49](https://github.com/opengeos/segment-geospatial/assets/5016453/056dc853-e954-4135-a57c-d78bf80eee67)

**Comment by amrsalah944** [comment]
@giswqs  I am hitting the same issue too 

https://github.com/user-attachments/assets/bd5f10cd-ecc3-48a1-8358-e7e6b397a7a7
