### ISSUE TITLE
SamGeo() cannot download model vit_h (samgeo.hq_sam)

### ISSUE THREAD

**Issue by aloboa** [opengeos/segment-geospatial#253]
At running 
```
sam = SamGeo(
    model_type="vit_h", # can be vit_h, vit_b, vit_l, vit_tiny
    sam_kwargs=None,
)
```
in
https://colab.research.google.com/github/opengeos/segment-geospatial/blob/main/docs/examples/automatic_mask_generator_hq.ipynb#scrollTo=6OwdcdWUvP1t  

I get:

```
FileURLRetrievalError: Cannot retrieve the public link of the file. You may need to change the permission to 'Anyone with the link', or have had many accesses.

During handling of the above exception, another exception occurred:

FileURLRetrievalError                     Traceback (most recent call last)

[/usr/local/lib/python3.10/dist-packages/gdown/download.py](https://localhost:8080/#) in download(url, output, quiet, proxy, speed, use_cookies, verify, id, fuzzy, resume, format, user_agent)
    241                 url_origin,
    242             )
--> 243             raise FileURLRetrievalError(message)
    244 
    245     if gdrive_file_id and is_gdrive_download_link:

FileURLRetrievalError: Failed to retrieve file url:

	Cannot retrieve the public link of the file. You may need to change
	the permission to 'Anyone with the link', or have had many accesses.

You may still be able to access the file from the browser:

	https://drive.google.com/uc?id=1qobFYrI4eyIANfBSmYcGuWRaSIXfMOQ8

but Gdown can't. Please check connections and permissions.
```
This used to work a few days ago.

**Comment by aloboa** [comment]
Tried several times and same result.
Regarding the 2nd option: considering I am running on colab, is that directory on my local machine?  If the directory is intended for the virtual machine, how can I actually creat it from within the .ipynb?

**Comment by giswqs** [comment]
The directory is for Colab. You can use os.make_dirs() to create it.

**Comment by aloboa** [comment]
Thanks, it would be useful to have this alternative in the example (https://samgeo.gishub.org/examples/automatic_mask_generator_hq/).
Also, why is this problem taking place?

**Comment by giswqs** [comment]
I will try to provide an alternative download.

**Comment by aloboa** [comment]
> I will try to provide an alternative download.

Great Thanks. 
By now I've done:
```
os.makedirs("~/.cache/torch/hub/checkpoints")
!wget https://drive.google.com/uc?id=1qobFYrI4eyIANfBSmYcGuWRaSIXfMOQ8 ~/.cache/torch/hub/checkpoints


```
but now I understand I still have to set `sam = SamGeo()`, but do not know how to specify not to download the model again but use the one I have downloaded instead. Also, I do not know if the downloaded model would be valid for other arguments. Therefore, I think I should wait for your extended example. Many thanks.

**Comment by giswqs** [comment]
Please upgrade to the latest version. The issue should be fixed now. 

![image](https://github.com/opengeos/segment-geospatial/assets/5016453/5cb40f19-8d4c-406e-82a9-946a1bfe6dd3)
