### ISSUE TITLE
"Input type uint16 is not supported" error on sam.generate

### ISSUE THREAD

**Issue by s-razavi** [opengeos/segment-geospatial#26]
thank you for the great work. I am trying to segment RGB from S2_SR. Downloaded tif file:
`geemap.ee_export_image(image.select(['B4', 'B3', 'B2']), filename='sr2.tif', scale=10, region=aoi)` 

added it to map by 
`m.add_raster(image, layer_name='Images')` 
and it works fine, tif exists and shows up.

at the stage of
`sam.generate(image, mask)`

gives me:

> TypeError: Input type uint16 is not supported

**Comment by giswqs** [comment]
Yes, SAM only supports `uint8` data type. You can convert tye uint16 to uint8 by dividing 65536. In the next samgeo release, I can add the automatic conversion if needed.

**Comment by giswqs** [comment]
If you use `geemap.ee_to_geotiff`, it will download the map tiles as uint8 

https://geemap.org/notebooks/134_ee_to_geotiff/

**Comment by s-razavi** [comment]
thanks. For some reasons:

> AttributeError: module 'geemap' has no attribute 'ee_to_geotiff'

**Comment by giswqs** [comment]
geemap.update_package()

**Comment by s-razavi** [comment]
Thank you.
