### ISSUE TITLE
exception when using box prompt

### ISSUE THREAD

**Issue by sanjivjha** [opengeos/segment-geospatial#261]
### Environment Information

-   samgeo version: latest
-   Python version: 3.10
-   Operating System: macos

### Description

TypeError: zip() argument after * must be an iterable, not NoneType

### What I Did
using example code from boxprompt. got same exception in both cases when ROI is selected and not selected

**Comment by giswqs** [comment]
I just tested the notebook example. It works fine on my end. 

https://samgeo.gishub.org/examples/box_prompts/

![image](https://github.com/user-attachments/assets/1ece9bf2-e82b-465b-82bf-627f885f5866)
