### ISSUE TITLE
SamGeoPredictor Geo_Box

### ISSUE THREAD

**Issue by BjornNyberg** [opengeos/segment-geospatial#27]
### Description

The geo_box parameter of the SamGeoPredictor.predict function seems to be hard coded to EPSG:4326 [here](https://github.com/opengeos/segment-geospatial/blob/c0ce7822b08f63e25feb4ea1aada6d6ffa528ff0/samgeo/samgeo.py#L448). It would be useful to allow for different projections.

In addition, this also causes problem when setting geo_box to None and using the [masks_to_geotiff](https://github.com/opengeos/segment-geospatial/blob/c0ce7822b08f63e25feb4ea1aada6d6ffa528ff0/samgeo/samgeo.py#LL466C9-L466C25) function considering width, height, geo_transform and crs are not previously defined.

**Comment by giswqs** [comment]
Good suggestion. Custom projection will be supported in the next release.

**Comment by giswqs** [comment]
The feature has been implemented. See the example below. Note that the `SamGeoPredictor` class will be deprecated. Use the `SamGeo` class instead. 

https://samgeo.gishub.org/examples/input_prompts/

```python
box = [-51.2552, -22.1761, -51.2538, -22.175]
# box = samgeo.bbox_to_xy('satellite.tif', box, "epsg:4326")  # optional step
sam = SamGeo(
    model_type="vit_h",
    checkpoint=checkpoint,
    automatic=False,
    sam_kwargs=None,
)
sam.predict(point_coords, point_labels, box=box, point_crs="EPSG:4326", output='mask.tif')
```
