### ISSUE TITLE
Is using headless opencv an option?

### ISSUE THREAD

**Issue by jrbourbeau** [opengeos/segment-geospatial#273]
Currently this project has `opencv-python` as a dependency, which requires `libgl` to be installed on linux. Hence the `apt install -y libgl1` recommendation in the install docs https://samgeo.gishub.org/installation/. I'm curious if using `opencv-python-headless` https://pypi.org/project/opencv-python-headless/ instead is feasible for this project. Maybe there's some functionality here where `opencv-python-headless` isn't sufficient, in which case I apologize for the noise here. If possible, switching to `opencv-python-headless` would make interoperability between linux and non-linux situations easier.

**Comment by giswqs** [comment]
Good suggestion. I think we should switch to `opencv-python-headless`. Would you like to submit a pull request to fix this? Thanks.
