### ISSUE TITLE
Automatic Mask Generator Batch Processing

### ISSUE THREAD

**Issue by BjornNyberg** [opengeos/segment-geospatial#28]
### Environment Information

Testing on the original notebook examples [here](https://samgeo.gishub.org/examples/satellite/), [here](https://samgeo.gishub.org/examples/automatic_mask_generator/) and [here](https://samgeo.gishub.org/examples/satellite-predictor/).

### Description

Im not sure if this is a design implementation or a bug but feel free to close if it is meant to behave in this way. Anyways I have noticed these issues: 

1) The Automatic Mask Generator of SAM does not work with the batch function set to True.
2) The sam.generate with an erosion_kernel set to None results in one mask for the entire region.
3) For the notebook example, sam_model_registry[model_type](checkpoint=checkpoint), does not automatically download checkpoints. Fixed with common.download_checkpoint(url,checkpoint)

### What I Did

```
 ##Automatic Mask Generator example from notebook
sam.generate(image, output='masks.tif', foreground=True, unique=True, batch=True)

#Satellite Example from notebook
sam = SamGeo(
    model_type='vit_h',
    checkpoint=checkpoint,
    erosion_kernel=None,
    mask_multiplier=255,
    sam_kwargs=None,
)
```

**Comment by giswqs** [comment]
@BjornNyberg Thank you for reporting. The patch processing bug should be fixed in #29. Note that the `SamGeoPredictor` class will be deprecated and merged into the `SamGeo` class in the next release. Stay tuned.
