### ISSUE TITLE
Failed to visulize the map

### ISSUE THREAD

**Issue by VoyagerXvoyagerx** [opengeos/segment-geospatial#281]
Thanks for your impressive work! 
I'm based in the mainland China. Unfortunately my machine could not access to google (that is, I failed to ping google, but could access to other websites like github). I'm not sure if this made me unable to visulize the base map and the imagery added to the map.
### Environment Information
- samgeo version: 0.10.5
- Python version: 3.10.0
- leafmap: 0.31.9
- Operating System: Ubuntu 22.04.3 LTS
- ipyevents                    2.0.2
- ipyfilechooser               0.6.0
- ipykernel                    6.29.4
- ipyleaflet                   0.19.0
- ipython                      8.24.0
- ipytree                      0.2.2
- ipywidgets                   8.1.2
- jupyter                      1.0.0
- jupyter_client               8.6.1
- jupyter-console              6.6.3
- jupyter_core                 5.7.2
- jupyter-events               0.10.0
- jupyter-leaflet              0.19.0
- jupyter-lsp                  2.2.5
- jupyter_server               2.14.0
- jupyter_server_terminals     0.5.3
- jupyterlab                   4.1.8
- jupyterlab_pygments          0.3.0
- jupyterlab_server            2.27.1
- jupyterlab_widgets           3.0.10

### Description
While executing the blocks below, No error was reported, but the map was blank.
```
m = leafmap.Map(center=[37.8713, -122.2580], zoom=17, height="800px")
m.add_basemap("SATELLITE")
m
```
```
m.add_raster
m = leafmap.Map(center=[37.8713, -122.2580], zoom=17, height="800px")
m.add_basemap("SATELLITE")
m
```
#### Environment setup
I created a new conda environment, and use pip install segment-geospatial to install the segment-geospatial package.
When installing segment-geospatial, it was reported that
```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
docker-compose 1.29.2 requires distro<2,>=1.5.0, which is not installed.
docker-compose 1.29.2 requires jsonschema<4,>=2.5.1, but you have jsonschema 4.22.0 which is incompatible.
docker-compose 1.29.2 requires PyYAML<6,>=3.10, but you have pyyaml 6.0.1 which is incompatible.
docker-compose 1.29.2 requires websocket-client<1,>=0.32.0, but you have websocket-client 1.8.0 which is incompatible.
```

![failed to show the map](https://github.com/opengeos/segment-geospatial/assets/67947949/56fb3bbc-ba27-4e1a-856c-f868cb7e9fb2)

Could you give me some advise? Thanks!

**Comment by VoyagerXvoyagerx** [comment]
Thanks to the souce code of leafmap, I solved the basemap problem by changing the basemap from `"SATELLITE"` to `Esri.WorldImagery`. However, I still failed to display the map after adding the satellite imagery.
```python
m.layers[-1].visible = False
m.add_raster(image, layer_name="Image")
m
```

**Comment by giswqs** [comment]
The default basemap is OpenStreetMap, which is also blocked in China. This is likely your network problem, not a samgeo problem.
