### ISSUE TITLE
Assistance Needed with ArcGIS Pro 3.3 

### ISSUE THREAD

**Issue by RossiHou** [opengeos/segment-geospatial#285]
### Environment Information

-   samgeo version: the lateset version
-   Python version: 3.11.8
-   Operating System: Win 11 (X64)

### Description

I am currently using the latest version of ArcGIS Pro 3.3 and attempting to utilize the Segment-Geospatial Python package for my research. However, I encountered an issue with the error message: "invalid choice: 'proswap'".
![图片](https://github.com/opengeos/segment-geospatial/assets/76504267/fe8dc689-b3b7-4979-878d-6d16aef4859c)

### What I Did

I suspect that the problem might be related to the Python packages when creating the environment as Issue #271
![图片](https://github.com/opengeos/segment-geospatial/assets/76504267/23671e27-b3b8-45aa-9977-34b2fe045d65)

**Comment by giswqs** [comment]
I suggest removing the existing geo env and start from scratch. I did that last week with ArcGIS Pro 3.3 and everything worked fine.

**Comment by RossiHou** [comment]
Hi Prof. Wu,

Thank you for your kind response. I followed your suggestion to reinstall the packages from the beginning. However, the problem has now changed to "Broken environment."
![图片](https://github.com/opengeos/segment-geospatial/assets/76504267/13cee816-8919-4e4b-9acd-ddf49eaa9a8c)
![图片](https://github.com/opengeos/segment-geospatial/assets/76504267/027a6b79-ea95-461b-bcdd-c4d87f9a5e07)

I even went reinstalling ArcGIS Pro and reinstalling the packages, but the issue persists, even after attempting to repair the environment.
![图片](https://github.com/opengeos/segment-geospatial/assets/76504267/4e894c44-6c1e-4069-bfec-463df6a7ae62)
![图片](https://github.com/opengeos/segment-geospatial/assets/76504267/ff27eabc-2620-473a-9717-fcb1664fc392)

Could you please provide further guidance on how to resolve this issue?

Thank you for your assistance.

**Comment by giswqs** [comment]
Did you remove the existing env before creating a new one?

conda remove -n geo --all

**Comment by giswqs** [comment]
The ArcGIS version updates keeps breaking the cloned envs. This is really an issue with ArcGIS rather than samgeo. I don't see the benefits of using samgeo with ArcGIS Pro. You can just run samgeo with JupyterLab and export the results to be visualized in ArcGIS if needed.

**Comment by RossiHou** [comment]
Understood, Many thanks for your valuable assistance Prof. Wu!

**Comment by RossiHou** [comment]
> The ArcGIS version updates keeps breaking the cloned envs. This is really an issue with ArcGIS rather than samgeo. I don't see the benefits of using samgeo with ArcGIS Pro. You can just run samgeo with JupyterLab and export the results to be visualized in ArcGIS if needed.

Understood, Many thanks for your valuable assistance Prof. Wu!
