### ISSUE TITLE
cuda error

### ISSUE THREAD

**Issue by gabengcuinirenne** [opengeos/segment-geospatial#299]
### Environment Information

-   samgeo version:
-   Python version:
-   Operating System:

### Description
If I want to crop my image first and then input it into the model, which method should I use in this code?

### What I Did

```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
```

**Comment by giswqs** [comment]
What cuda error? You need to provide some details.

**Comment by gabengcuinirenne** [comment]
![Uploading feb7b6887de4583ec70313222b89b43.png…]()

**Comment by gabengcuinirenne** [comment]
**Error:** torch.OutofMemoryError: CUDA out of memory. Tried to allocate 84.20 GiB. GPU 0 has a total capacity of 47.54 GiB of whi ich 43.61 GiB is free. Process 13444 has 3.92 GiB memory in use. Of the allocated memory 3.28 GiB is allocated by PyTorch, and 338.17 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is lar arge try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation. See documentation for Memory Management(https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
By the way, my input image is a UAV images, only 445M, but when I crop my image by arcmap ,I can get the output, So I want to crop the images in batches and then import them into the sam one by one, and the final result is a combined result.

**Comment by giswqs** [comment]
As @brendancol suggested, you can use the `predict_batch` function to segment a large image. Alternatively, you can split the image on your own and then use samgeo to segment the smaller tiles.
