### ISSUE TITLE
Add support for SAM 2

### ISSUE THREAD

**Issue by giswqs** [opengeos/segment-geospatial#300]
https://github.com/facebookresearch/segment-anything-2

https://github.com/lujiazho/SegDrawer

**Comment by amjadraza** [comment]
Looking forward to it.

**Comment by lionelhorn** [comment]
I was about to ask if this repo would gain anything to add SAM2. And here I see you already made an issue :)

Would segment-geospatial benefit from SAM2 new capabilities?

**Comment by giswqs** [comment]
SAM 2 has installation issues at the moment. I am going to wait for Hugging Face transformers to add support for SAM 2. That will make it easier to integrate SAM 2 into SAMGeo. 
https://github.com/huggingface/transformers/issues/32308

**Comment by SFrav** [comment]
Would predicting on a timeseries with SAM2 improve the accuracy of any individual frame when compared to a single image?

**Comment by skylning** [comment]
Looking forward to it.

**Comment by giswqs** [comment]
Waiting for PR to be merged. Then we can add support for SAM 2.
https://github.com/huggingface/transformers/pull/32394

**Comment by giswqs** [comment]
I have added sam2 to conda-forge. Will be working on integrating sam2 into samgeo. 
https://anaconda.org/conda-forge/sam2

**Comment by jamescrowley** [comment]
@giswqs if there are ways to support the effort integrating sam2, I'd be happy to help

**Comment by giswqs** [comment]
@jamescrowley Awesome! I plan to start working on it tomorrow. Hope to submit the PR soon. Feedback, suggestions, and contributions are very welcome.

**Comment by jamescrowley** [comment]
Awesome, thanks @giswqs! 🎉
