### ISSUE TITLE
segment and vector outputs are single value

### ISSUE THREAD

**Issue by calebpan** [opengeos/segment-geospatial#34]
### Environment Information

-   samgeo version: segment_geospatial-0.4.0-py2.py3-none-any.whl
-   Python version: 3.1
-   Operating System: Windows 10

### Description

Ran the example code provided in both pycharm on local machine and in Google Colab here:
https://colab.research.google.com/github/opengeos/segment-geospatial/blob/main/docs/examples/satellite.ipynb#scrollTo=Gqby0rFINPNR

Output vectors and segments return single value of 255. Does not return the same output as shown in example.

![image](https://github.com/opengeos/segment-geospatial/assets/12896439/d4f5ce3d-be52-4a21-88da-41d4469e6295)

### What I Did

```
import os
from samgeo import SamGeo, tms_to_geotiff, get_basemaps
bbox = [-122.0142108,37.0539328,-122.0129377,37.0554187]

image = 'satellite_v6.tif'
shapefile = "segment_v6.shp"
mask = 'segment_v6.tif'
tms_to_geotiff(output=image, bbox = bbox, zoom=20, source="Satellite", overwrite=True)

# '''
# Initialize SAM class
# '''
out_dir = os.path.join(os.path.expanduser("~"), "Downloads")
checkpoint = os.path.join(out_dir, "sam_vit_h_4b8939.pth")

sam = SamGeo(
   model_type="vit_h",
   checkpoint=checkpoint,
   sam_kwargs=None,
)
#
# '''
# Segment the image
# Set batch=True to segment the image in batches. This is useful for large images that cannot fit in memory.
# '''
print('Generating segments...')

sam.generate(
   image, mask, batch=True, foreground=True, erosion_kernel=(3, 3), mask_multiplier=255
)

# '''
# Polygonize the raster data
# Save the segmentation results as a GeoPackage file.
# '''
print('Creating shapefile...')
sam.tiff_to_vector(mask, shapefile)
```

Returns same results as in the Colab example.

**Comment by giswqs** [comment]
This bug has been fixed in https://github.com/opengeos/segment-geospatial/pull/29, but it has not been released to PyPI yet. You can run the following to install it from GitHub. Otherwise, wait until the next release later this week. 

```bash
pip install git+https://github.com/opengeos/segment-geospatial.git
```

**Comment by giswqs** [comment]
Or install v0.3.0. 

```python
pip install segment-geospatial==0.3.0
```

**Comment by calebpan** [comment]
In line. resintalled version 0.3.0

sam.generate() returns an error:
mask = "segment.tiff"
sam.generate(
    image, mask, batch=True, foreground=True, erosion_kernel=(3, 3), mask_multiplier=255
)

TypeError                                 Traceback (most recent call last)
[<ipython-input-13-e5de2ee1a9e8>](https://localhost:8080/#) in <cell line: 2>()
      1 mask = "segment.tiff"
----> 2 sam.generate(
      3     image, mask, erosion_kernel=(3, 3), mask_multiplier=255
      4 )

[/usr/local/lib/python3.10/dist-packages/samgeo/samgeo.py](https://localhost:8080/#) in generate(self, in_path, out_path, **kwargs)
    110         """
    111 
--> 112         return tiff_to_tiff(in_path, out_path, self, **kwargs)
    113 
    114     def image_to_image(self, image, **kwargs):

TypeError: tiff_to_tiff() got an unexpected keyword argument 'erosion_kernel'

**Comment by giswqs** [comment]
It is probably because the notebook has been updated. It is no longer compatible with v0.3. Try installing from Github

**Comment by calebpan** [comment]
You're right, thank you
