### ISSUE TITLE
geemap breaks when SamGeo is imported

### ISSUE THREAD

**Issue by dfguerrerom** [opengeos/segment-geospatial#342]
### To reproduce

```python
import os
from samgeo import SamGeo

Map = geemap.Map()
```
it prints out the following error:

RuntimeError: Error creating a Maps API session:
{'error': {'code': 400, 'message': 'API key not valid. Please pass a valid API key.', 'errors': [{'message': 'API key not valid. Please pass a valid API key.', 'domain': 'global', 'reason': 'badRequest'}], 'status': 'INVALID_ARGUMENT', 'details': [{'@type': 'type.googleapis.com/google.rpc.ErrorInfo', 'reason': 'API_KEY_INVALID', 'domain': 'googleapis.com', 'metadata': {'service': 'tile.googleapis.com'}}]}}.

I found out that the culprit is this line https://github.com/opengeos/segment-geospatial/blob/513020a46f1d6701ccdb026c02ffcc3d32f931db/samgeo/common.py#L17, any reason to have that there?

**Comment by giswqs** [comment]
I just released v0.12.1. Please try again.

**Comment by dfguerrerom** [comment]
thanks!!
