### ISSUE TITLE
Docker Image missing libs

### ISSUE THREAD

**Issue by guillemc23** [opengeos/segment-geospatial#344]
I am trying to use the docker image `giswqs/segment-geospatial:latest` as a devcontainer to test SAMGEO.  I have encountered some problems when importing dependencies such as OpenCV which I believe are related to the base image used missing some needed libraries.

I think it should be as simple as running the following command:
```bash
apt-get update && apt-get install libgl1
```
I am unable to start the container and run it myself since I need sudo access, which is not granted by default.

**Comment by giswqs** [comment]
Can you submit a pull request? Thanks

**Comment by giswqs** [comment]
Yes

**Comment by giswqs** [comment]
Fixed in #356
