### ISSUE TITLE
'predict_by_points' function

### ISSUE THREAD

**Issue by narges-tk** [opengeos/segment-geospatial#347]
### Environment Information

-   samgeo version:
-   Python version:
-   Operating System:

### Description

Describe what you were trying to get done.
Tell us what happened, what went wrong, and what you expected to happen.

### What I Did

```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
```

**Comment by narges-tk** [comment]
Hi!
Thanks for your nice work and continued updates! I am facing the following error:
**AttributeError: 'SamGeo2' object has no attribute 'predict_by_points'**
I also tried to re-install SAM geo to see if the updates appear or not. However, I faced the installation problem below:
  **Using cached sam2-0.4.0.tar.gz (75 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
  Using cached sam2-0.3.0.tar.gz (75 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
ERROR: Cannot install segment-geospatial because these package versions have conflicting dependencies.

The conflict is caused by:
    sam2 0.4.1 depends on torchvision>=0.18.1
    sam2 0.4.0 depends on torchvision>=0.18.1
    sam2 0.3.0 depends on torchvision>=0.18.1

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip to attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts**

Thanks in advance for your help!

**Comment by giswqs** [comment]
This is your own conda env problem. Try creating a fresh conda env to install samgeo or use Google Colab.
https://samgeo.gishub.org/examples/sam2_point_prompts/

**Comment by narges-tk** [comment]
> This is your own conda env problem. Try creating a fresh conda env to install samgeo or use Google Colab. https://samgeo.gishub.org/examples/sam2_point_prompts/

Many thanks for your prompt reply. It's working nicely in Google Colab!
