### ISSUE TITLE
minzoom error adding raster on SAM2 Point Prompts

### ISSUE THREAD

**Issue by LeoCerquera** [opengeos/segment-geospatial#351]
Im running the Colab for SAM2 Point Promts, I have not modified any cells, I have just executed it. in the step "Display the downloaded image on the map": 

            m.layers[-1].visible = False
            m.add_raster(image, layer_name="Image")
            m

return this error:

            KeyError                                  Traceback (most recent call last)
            [/usr/local/lib/python3.10/dist-packages/pydantic/main.py](https://localhost:8080/#) in __getattr__(self, item)
                847                     try:
            --> 848                         return pydantic_extra[item]
                849                     except KeyError as exc:
            
            KeyError: 'minzoom'
            
            The above exception was the direct cause of the following exception:
            
            AttributeError                            Traceback (most recent call last)
            4 frames
            [<ipython-input-10-0ba2154fe6a1>](https://localhost:8080/#) in <cell line: 2>()
                  1 m.layers[-1].visible = False
            ----> 2 m.add_raster(image, layer_name="Image")
                  3 m
            
            [/usr/local/lib/python3.10/dist-packages/leafmap/leafmap.py](https://localhost:8080/#) in add_raster(self, source, indexes, colormap, vmin, vmax, nodata, attribution, layer_name, layer_index, zoom_to_layer, visible, opacity, array_args, client_args, **kwargs)
               2377         if zoom_to_layer:
               2378             self.center = tile_client.center()
            -> 2379             self.zoom = tile_client.default_zoom
               2380 
               2381         arc_add_layer(tile_layer.url, layer_name, True, 1.0)
            
            [/usr/local/lib/python3.10/dist-packages/localtileserver/client.py](https://localhost:8080/#) in default_zoom(self)
                 98     @property
                 99     def default_zoom(self):
            --> 100         return self.min_zoom
                101 
                102     def bounds(
            
            [/usr/local/lib/python3.10/dist-packages/localtileserver/client.py](https://localhost:8080/#) in min_zoom(self)
                 90     @property
                 91     def min_zoom(self):
            ---> 92         return self.info.minzoom
                 93 
                 94     @property
            
            [/usr/local/lib/python3.10/dist-packages/pydantic/main.py](https://localhost:8080/#) in __getattr__(self, item)
                848                         return pydantic_extra[item]
                849                     except KeyError as exc:
            --> 850                         raise AttributeError(f'{type(self).__name__!r} object has no attribute {item!r}') from exc
                851                 else:
                852                     if hasattr(self.__class__, item):
            
            AttributeError: 'Info' object has no attribute 'minzoom'

**Comment by SaltyPoseidon** [comment]
I'm having the same problem
