### ISSUE TITLE
while using SAM2 point prompts, getting AttributeError: module 'tensorflow.python.distribute.input_lib' has no attribute 'DistributedDatasetInterface'

### ISSUE THREAD

**Issue by ajayvsv** [opengeos/segment-geospatial#358]
While trying to execute SAM2 point prompts : I am getting this error. 
Note: in Ubuntu22 system

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
[/tmp/ipykernel_5425/1846741878.py](http://localhost:8888/tmp/ipykernel_5425/1846741878.py) in <module>
      1 # training model
----> 2 history = model.fit(train_xx, train_yy, validation_data=(test_xx, test_yy), epochs=100, batch_size=10, verbose=1)

~/.local/lib/python3.10/site-packages/tensorflow/python/keras/engine/training.py in fit(self, x, y, batch_size, epochs, verbose, callbacks, validation_split, validation_data, shuffle, class_weight, sample_weight, initial_epoch, steps_per_epoch, validation_steps, validation_batch_size, validation_freq, max_queue_size, workers, use_multiprocessing)
   1135          training_utils.RespectCompiledTrainableState(self):
   1136       # Creates a `tf.data.Dataset` and handles batch and epoch iteration.
-> 1137       data_handler = data_adapter.get_data_handler(
   1138           x=x,
   1139           y=y,

~/.local/lib/python3.10/site-packages/tensorflow/python/keras/engine/data_adapter.py in get_data_handler(*args, **kwargs)
   1395   if getattr(kwargs["model"], "_cluster_coordinator", None):
   1396     return _ClusterCoordinatorDataHandler(*args, **kwargs)
-> 1397   return DataHandler(*args, **kwargs)
   1398 
   1399 

~/.local/lib/python3.10/site-packages/tensorflow/python/keras/engine/data_adapter.py in __init__(self, x, y, sample_weight, batch_size, steps_per_epoch, initial_epoch, epochs, shuffle, class_weight, max_queue_size, workers, use_multiprocessing, model, steps_per_execution, distribute)
   1149       self._steps_per_execution_value = steps_per_execution.numpy().item()
   1150 
-> 1151     adapter_cls = select_data_adapter(x, y)
   1152     self._adapter = adapter_cls(
   1153         x,

~/.local/lib/python3.10/site-packages/tensorflow/python/keras/engine/data_adapter.py in select_data_adapter(x, y)
    985 def select_data_adapter(x, y):
    986   """Selects a data adapter than can handle a given x and y."""
--> 987   adapter_cls = [cls for cls in ALL_ADAPTER_CLS if cls.can_handle(x, y)]
    988   if not adapter_cls:
    989     # TODO(scottzhu): This should be a less implementation-specific error.

~/.local/lib/python3.10/site-packages/tensorflow/python/keras/engine/data_adapter.py in <listcomp>(.0)
    985 def select_data_adapter(x, y):
    986   """Selects a data adapter than can handle a given x and y."""
--> 987   adapter_cls = [cls for cls in ALL_ADAPTER_CLS if cls.can_handle(x, y)]
    988   if not adapter_cls:
    989     # TODO(scottzhu): This should be a less implementation-specific error.

~/.local/lib/python3.10/site-packages/tensorflow/python/keras/engine/data_adapter.py in can_handle(x, y)
    704   def can_handle(x, y=None):
    705     return (isinstance(x, (data_types.DatasetV1, data_types.DatasetV2)) or
--> 706             _is_distributed_dataset(x))
    707 
    708   def __init__(self,

~/.local/lib/python3.10/site-packages/tensorflow/python/keras/engine/data_adapter.py in _is_distributed_dataset(ds)
   1694 
   1695 def _is_distributed_dataset(ds):
-> 1696   return isinstance(ds, input_lib.DistributedDatasetInterface)

AttributeError: module 'tensorflow.python.distribute.input_lib' has no attribute 'DistributedDatasetInterface'

**Comment by giswqs** [comment]
samgeo does not use tensorflow. This is your own python env problem. Follow the instructions [here](https://samgeo.gishub.org/installation/#install-from-conda-forge) to create a fresh conda env to install samgeo.
