### ISSUE TITLE
segment-geospatial failed to give results/output

### ISSUE THREAD

**Issue by ajayvsv** [opengeos/segment-geospatial#359]
Trying to use  segment-geospatial (https://samgeo.gishub.org/usage/) 

This is performing well, to my given extent by downloading a satellite image of about (1sqkm, zoom level 16+)

Bug1: for my area about 5sqkm, it fails. (zoom level: 16+)

Bug2: failed to give result/output for my given satellite imagery. (tried with my choice of raster below 1sqkm upto 5sqkm)
( in this, after successful execution, it just gives ....  
_Python 3.10.12 (main, Sep 11 2024, 15:47:36) [GCC 11.4.0]
Type 'copyright', 'credits' or 'license' for more information
IPython 7.31.1 -- An enhanced Interactive Python. Type '?' for help._)

**Comment by giswqs** [comment]
See https://github.com/opengeos/segment-geospatial?tab=readme-ov-file#legal-notice
