### ISSUE TITLE
Unable to Manually Edit Boxes after Uploading .geojson File in SAM2 Box Prompts Example

### ISSUE THREAD

**Issue by Pengyu-gis** [opengeos/segment-geospatial#360]
Thank you for this great repository! I encountered an issue while following the "**SAM2 Box Prompts**" example. After uploading a `.geojson` file with box prompts, I wanted to manually edit some of the boxes, but it seems that this feature is currently not supported.
```py
url = "https://github.com/opengeos/datasets/releases/download/samgeo/building_bboxes.geojson"
geojson = "building_bboxes.geojson"
leafmap.download_file(url, geojson)

m = leafmap.Map()
m.add_raster(image, layer_name="Image")
style = {
    "color": "#ffff00",
    "weight": 2,
    "fillColor": "#7c4185",
    "fillOpacity": 0,
}
m.add_vector(geojson, style=style, zoom_to_layer=True, layer_name="Bboxes")
m
```
![image](https://github.com/user-attachments/assets/2632d7a5-7584-4e83-8299-37989751e670)

**Comment by giswqs** [comment]
See https://leafmap.org/notebooks/46_edit_vector
