### ISSUE TITLE
How to solver warning libmamba

### ISSUE THREAD

**Issue by dheejaysantos15** [opengeos/segment-geospatial#365]
Hi, 

I would like to ask how to solve the libmamba warning and the critical libmamba error while installing the samgeo.

Here is a screenshot of the error that I have encountered during the installation. Thank you. 

![Error Screenshot](https://github.com/user-attachments/assets/2d17dbb0-f8e2-4acd-9c2f-744988d436ab)

**Comment by giswqs** [comment]
This is not really a samgeo issue, but a general mamba issue. Please report it to https://github.com/mamba-org/mamba/issues.
