### ISSUE TITLE
TypeError: SamGeo.__init__() got an unexpected keyword argument 'erosion_kernel'

### ISSUE THREAD

**Issue by Mrzeng1** [opengeos/segment-geospatial#37]
The following error is prompted when using the sample code：
Traceback (most recent call last):
  File "C:\Users\Administrator\PycharmProjects\pythonProject\main.py", line 14, in <module>
    sam = SamGeo(
TypeError: SamGeo.__init__() got an unexpected keyword argument 'erosion_kernel'

**Comment by giswqs** [comment]
The package has changed a lot for the past releases. Please make sure you download the latest notebooks. 
https://samgeo.gishub.org/examples/satellite/
