### ISSUE TITLE
Installation errors

### ISSUE THREAD

**Issue by tnmthai** [opengeos/segment-geospatial#373]
I tried various methods on both Windows and Linux, using both Conda and regular Python, but I still encountered errors. See below:
```
pip install segment-geospatial
```

Collecting git+https://github.com/opengeos/segment-geospatial
  Cloning https://github.com/opengeos/segment-geospatial to [c:\users\trant\appdata\local\temp\pip-req-build-4o96yej_](file:///C:/users/trant/appdata/local/temp/pip-req-build-4o96yej_)
  Resolved https://github.com/opengeos/segment-geospatial to commit 1157a6c8df545f70e7859aaa48f4c810fa15f4fe
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Collecting fiona (from segment-geospatial==0.12.3)
  Using cached fiona-1.10.1-cp313-cp313-win_amd64.whl.metadata (58 kB)
Collecting gdown (from segment-geospatial==0.12.3)
  Using cached gdown-5.2.0-py3-none-any.whl.metadata (5.8 kB)
Collecting geopandas (from segment-geospatial==0.12.3)
  Using cached geopandas-1.0.1-py3-none-any.whl.metadata (2.2 kB)
Collecting huggingface_hub (from segment-geospatial==0.12.3)
  Using cached huggingface_hub-0.26.2-py3-none-any.whl.metadata (13 kB)
Collecting ipympl (from segment-geospatial==0.12.3)
  Using cached ipympl-0.9.4-py3-none-any.whl.metadata (8.7 kB)
Collecting leafmap (from segment-geospatial==0.12.3)
  Using cached leafmap-0.41.1-py2.py3-none-any.whl.metadata (16 kB)
Collecting localtileserver (from segment-geospatial==0.12.3)
  Using cached localtileserver-0.10.5-py3-none-any.whl.metadata (5.2 kB)
Collecting matplotlib (from segment-geospatial==0.12.3)
  Using cached matplotlib-3.9.2-cp313-cp313-win_amd64.whl.metadata (11 kB)
Collecting opencv-python-headless (from segment-geospatial==0.12.3)
  Using cached opencv_python_headless-4.10.0.84-cp37-abi3-win_amd64.whl.metadata (20 kB)
Collecting patool (from segment-geospatial==0.12.3)
  Using cached patool-3.1.0-py2.py3-none-any.whl.metadata (4.3 kB)
Collecting pycocotools (from segment-geospatial==0.12.3)
  Using cached pycocotools-2.0.8.tar.gz (24 kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Collecting pyproj (from segment-geospatial==0.12.3)
  Using cached pyproj-3.7.0-cp313-cp313-win_amd64.whl.metadata (31 kB)
Collecting rasterio (from segment-geospatial==0.12.3)
  Using cached rasterio-1.4.2-cp313-cp313-win_amd64.whl.metadata (9.4 kB)
Collecting rioxarray (from segment-geospatial==0.12.3)
  Using cached rioxarray-0.18.1-py3-none-any.whl.metadata (5.4 kB)
Collecting sam2 (from segment-geospatial==0.12.3)
  Using cached sam2-0.4.1.tar.gz (75 kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'error'
  Running command git clone --filter=blob:none --quiet https://github.com/opengeos/segment-geospatial 'C:\Users\trant\AppData\Local\Temp\pip-req-build-4o96yej_'
  error: subprocess-exited-with-error
  
  × pip subprocess to install build dependencies did not run successfully.
  │ exit code: 1
  ╰─> [4 lines of output]
      Collecting setuptools>=61.0
        Using cached setuptools-75.6.0-py3-none-any.whl.metadata (6.7 kB)
      ERROR: Could not find a version that satisfies the requirement torch>=2.3.1 (from versions: none)
      ERROR: No matching distribution found for torch>=2.3.1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× pip subprocess to install build dependencies did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

**Comment by giswqs** [comment]
Please use conda to install packages on Windows. You will have a hard time trying to install torch related packages on Windows using pip. 

See https://samgeo.gishub.org/installation/#install-from-conda-forge
