### ISSUE TITLE
Error while downloading Google Satellite imagery of large area (around 5km by 5km)

### ISSUE THREAD

**Issue by ravishbapna** [opengeos/segment-geospatial#4]
---------------------------------------------------------------------------
MemoryError                               Traceback (most recent call last)
File ~\miniconda3\envs\gee\lib\site-packages\samgeo\common.py:523, in tms_to_geotiff(output, bbox, zoom, resolution, source, to_cog, return_image, overwrite, quiet, **kwargs)
    522 try:
--> 523     image = draw_tile(
    524         source, south, west, north, east, zoom, output, quiet, **kwargs
    525     )
    526     if return_image:

File ~\miniconda3\envs\gee\lib\site-packages\samgeo\common.py:512, in tms_to_geotiff.<locals>.draw_tile(source, lat0, lon0, lat1, lon1, zoom, filename, quiet, **kwargs)
    511 for band in range(imgbands):
--> 512     array = numpy.array(img.getdata(band), dtype="u8")
    513     array = array.reshape((img.size[1], img.size[0]))

MemoryError: Unable to allocate 6.89 GiB for an array with shape (924972736,) and data type uint64

During handling of the above exception, another exception occurred:

Exception                                 Traceback (most recent call last)
Cell In[7], line 2
      1 # Download image as GeoTiff
----> 2 tms_to_geotiff(output=output_image, bbox=bbox, resolution=spatial_resolution, source=data_source,quiet=False)

File ~\miniconda3\envs\gee\lib\site-packages\samgeo\common.py:531, in tms_to_geotiff(output, bbox, zoom, resolution, source, to_cog, return_image, overwrite, quiet, **kwargs)
    529         image_to_cog(output, output)
    530 except Exception as e:
--> 531     raise Exception(e)

Exception: Unable to allocate 6.89 GiB for an array with shape (924972736,) and data type uint64

**Comment by giswqs** [comment]
The error message is very clear. You need a computer with more memory or you need to try a smaller area

**Comment by ravishbapna** [comment]
Laptop has 16GB RAM and 42GB free C: hard disk space. I am confused if more space is required.

**Comment by giswqs** [comment]
There are intermediate steps that sometimes requires memory several times of the file size. You are welcome to inspect the source code and submit a pull request to improve it.
