### ISSUE TITLE
Generating object masks from input prompts with SAM

### ISSUE THREAD

**Issue by felipenorconsult** [opengeos/segment-geospatial#45]
### Environment Information

-   samgeo version: 0.5
-   Python version:
-   Operating System:

### Description

Generating object masks from input prompts with SAM in the interactive part:
while running this line as described:
m = sam.show_map()
m
I got this error:

![image](https://github.com/opengeos/segment-geospatial/assets/123383337/e08fd869-7eb3-40ea-bcf1-29c8f0877d3a)

**Comment by giswqs** [comment]
Try out the new version on Colab: https://samgeo.gishub.org/examples/input_prompts

Your error seems a [localtileserver](https://github.com/banesullivan/localtileserver) problem.
