### ISSUE TITLE
Integrated into qgis

### ISSUE THREAD

**Issue by kamen007** [opengeos/segment-geospatial#46]
Hi，It‘s really great work! 
Could you please tell me how to integratethis work into qgis software?
Many thanks~

**Comment by BjornNyberg** [comment]
@kamen007 

The products produced by samgeo can be directly imported into QGIS (geopackage, geotiff). For example, based on this [notebook](https://samgeo.gishub.org/examples/satellite/) use
```
vector = "segment.gpkg"
sam.tiff_to_gpkg(mask, vector, simplify_tolerance=None)

shapefile = "segment.shp"
sam.tiff_to_vector(mask, shapefile)
```
For direct integration within QGIS, you may want to check out this [plugin](
https://github.com/BjornNyberg/Geometric-Attributes-Toolbox/wiki/User-Guide#segment-anything-model).

**Comment by giswqs** [comment]
Thank you @BjornNyberg for sharing the QGIS Plugin. I have added it to the README. 
https://github.com/opengeos/segment-geospatial#using-sam-with-desktop-gis
