### ISSUE TITLE
Error when saving output: 'Map' object has no attribute 'file_control' in V0.6.0 -  Generating object masks from input prompts with SAM

### ISSUE THREAD

**Issue by YunyaGaoTree** [opengeos/segment-geospatial#47]
line 1951 in /samgeo/common.py -  https://github.com/opengeos/segment-geospatial/pull/44/files

[/content/drive/MyDrive/samgeo/common.py](https://localhost:8080/#) in save_button_click(change)
   1980                 m.file_control = file_control
   1981         else:
-> 1982             if m.file_control in m.controls:
   1983                 m.remove_control(m.file_control)
   1984                 delattr(m, "file_control")

AttributeError: 'Map' object has no attribute 'file_control'

**Comment by YunyaGaoTree** [comment]
Hello everyone, I met a problem when saving output from sam.show_map() by using my own data. (as the following figure shows)

Actually I am not sure whether I use the right 0.6.0 version because the toolbar looks different from the tutorial on YouTube https://www.youtube.com/watch?v=bcOs0jQ5xFA.

I used the updated version of /samgeo/common.py and samgeo.py  from this link  https://github.com/opengeos/segment-geospatial/pull/44/files to replace the scripts in v0.5.0.

Besides, the output results are not promising when I use this image as input data. Actually, it is even worse than the output without any interaction from this notebook https://samgeo.gishub.org/examples/satellite-predictor/. 
If you have any suggestions, welcome to let me know. 
Thanks so much in advance!

![2023-05-16 15_53_00-SAM4Geospatial_Interactive ipynb - Colaboratory](https://github.com/opengeos/segment-geospatial/assets/101531630/b95ee1c0-8f01-404f-94e9-bdd959a1a07a)

**Comment by giswqs** [comment]
Try running `samgeo.update_package()` to install the development version from GitHub. Segment-geospatial uses the SAM model under the hood. If the performance is better when using SAM directly without the samgeo, then it is a samgeo problem. Otherwise, it is a SAM problem.

**Comment by giswqs** [comment]
Try out v0.6.0.
