### ISSUE TITLE
Add support for input prompts such as points or boxes

### ISSUE THREAD

**Issue by giswqs** [opengeos/segment-geospatial#5]
For now, segment-geospatial segments the entire image. It would be great to add support for input prompts such as points or boxes. This will be useful for extracting specific features from satellite imagery, such as buildings, roads, waterbodies, etc.

![image](https://user-images.githubusercontent.com/5016453/233814589-e953b8c7-7b25-4008-954f-c5c9d3a7942a.png)

![image](https://user-images.githubusercontent.com/5016453/233814597-27b139d4-d5b3-48f5-987d-5f5d13177e03.png)

![image](https://user-images.githubusercontent.com/5016453/233814600-98d52343-3b64-441a-8d6d-985ff11b82b5.png)

**Comment by austinmw** [comment]
+1 would love support for input bbox prompts since I already have a strong detector

**Comment by Havi-muro** [comment]
If I understood right, you can load your points in the argument point_grids as a list(np.ndarray) of normalized pixel coordinates.  I'm not sure to what extent it is useful or if it worked in my case, since there was very little difference with respect to using the default grid of points.
