### ISSUE TITLE
"ImportError: libLerc.so.4: cannot open shared object file: No such file or directory" when importing samgeo

### ISSUE THREAD

**Issue by rajkifranciska** [opengeos/segment-geospatial#53]
### Environment Information

- segment-anything-py version:  1.0
- segment-geospatial version: 0.5.0
- Python version: 3.8.16
- torch version: 2.0.0
- GDAL version: 3.5.3
- rasterio version: 1.3.3

### Description
I tried to run the segmentation tutorial. I think I'm in some kind of dependency hell, as I've been trying to run this for a few days now, and based on the order of the imports in the DockerFile, I get different errors. 

I work from a Dockern container, the DockerFile looks like this:

FROM nvidia/cuda:11.7.1-devel-ubuntu22.04
ENV CUDA_HOME=/usr/local/cuda-11.7
ENV PATH=/usr/local/cuda-11.7/bin:$PATH
ENV LD_LIBRARY_PATH=/usr/local/cuda-11.7/lib64:$LD_LIBRARY_PATH

RUN apt-get update && apt-get install wget ffmpeg libsm6 libxext6 -y

ENV CONDA_DIR /opt/conda
RUN wget --quiet https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O ~/miniconda.sh && \
     /bin/bash ~/miniconda.sh -b -p /opt/conda

ENV PATH=$CONDA_DIR/bin:$PATH

RUN conda install -n base mamba -c conda-forge
RUN mamba create -n geo python==3.8 -c conda-forge
RUN conda install -y -n geo pytorch==2.0.0 torchvision torchaudio pytorch-cuda=11.7 -c pytorch -c nvidia
RUN mamba install -n geo segment-geospatial -c conda-forge -vv
RUN mamba install -n geo leafmap geopandas localtileserver -c conda-forge
RUN conda install -n geo gdal -c conda-forge 

RUN conda init bash

### What I Did
I got stuck at the imports with the following Error:
```
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
Cell In[4], line 1
----> 1 from samgeo import SamGeo, tms_to_geotiff, get_basemaps

File /opt/conda/envs/geo/lib/python3.8/site-packages/samgeo/__init__.py:8
      4 __email__ = 'giswqs@gmail.com'
      5 __version__ = '0.5.0'
----> 8 from .samgeo import *

File /opt/conda/envs/geo/lib/python3.8/site-packages/samgeo/samgeo.py:11
      8 import numpy as np
      9 from segment_anything import sam_model_registry, SamAutomaticMaskGenerator, SamPredictor
---> 11 from .common import *
     14 class SamGeo:
     15     """The main class for segmenting geospatial data with the Segment Anything Model (SAM). See
     16     https://github.com/facebookresearch/segment-anything for details.
     17     """

File /opt/conda/envs/geo/lib/python3.8/site-packages/samgeo/common.py:13
     11 import shapely
     12 import pyproj
---> 13 import rasterio
     14 import geopandas as gpd
     15 import matplotlib.pyplot as plt

File /opt/conda/envs/geo/lib/python3.8/site-packages/rasterio/__init__.py:28
     24                     os.add_dll_directory(p)
     27 from rasterio._show_versions import show_versions
---> 28 from rasterio._version import gdal_version, get_geos_version, get_proj_version
     29 from rasterio.crs import CRS
     30 from rasterio.drivers import driver_from_extension, is_blacklisted

ImportError: libLerc.so.4: cannot open shared object file: No such file or directory
```

**Comment by giswqs** [comment]
Try removing `RUN conda install -n geo gdal -c conda-forge`. Installing localtileser should automatically install gdal.

**Comment by giswqs** [comment]
Also try Python 3.9 and Python 3.10. I am not sure if Python 3.8 is the problem. This appears to be a rasterio installation problem rather than segment-geospatial. I suggest removing those lines for package installation and only use `RUN mamba install -n geo rasterio -c conda-forge`. Test `import rasterio` and make sure no import erorr. Otherwise, segment-geospatial would not work either.
