### ISSUE TITLE
Segment non-geospatial raster imagery in png or tif format

### ISSUE THREAD

**Issue by rbavery** [opengeos/segment-geospatial#64]
### Description

I'd like to segment non geospatial raster imagery, or have segment-geospatial handle dummy georeferencing for png images so that they can be loaded into the interactive segmentation UI. Currently, PNGs can be loaded into the image comparison tool from leafmap. But when trying to start the interactive UI, non georeferenced imagery does not show up after calling 

```
sam.set_image("path/to/png")
same.show_map()
```

I've tried to georeference an image and plot it, but because I'm using a remote jupyterlab instance, I see a flicker and then a map at full zoom. Following the suggestion of including a localtileserver config:

```
import os
os.environ['LOCALTILESERVER_CLIENT_PREFIX'] = 'proxy/{port}'
m.layers[-1].visible = False
m.add_raster(result['HR_path'].split(".png")[0]+".tif", center=[origin[1], origin[0]], layer_name="Image")
m
```

unfortunately didn't help and produced the same result.

**Comment by giswqs** [comment]
Unfortunately, I don't think the interactive segmentation UI would work for non-georeferenced imagery. We need to convert the latlon coordinates of mouse clicked locations to row and column number of an image. Non-georeferenced imagery does not have lat/lon information. 

The following example is a potential workaround for non-georeferenced imagery. Left-clicking on the image will add a green dot and right-clicking adds a red dots. The point coordinates (x,y) can be returned and passed back to the `predict` function. It is not as interactive/intuitive as leafmap, but at least you can create markers interactively. 

```python
import cv2
import numpy as np

# Load the image
image = cv2.imread('satellite.tif')

# Create an empty list to store the mouse click coordinates
left_clicks = []
right_clicks = []

# Create a mouse callback function
def get_mouse_coordinates(event, x, y, flags, param):
    if event == cv2.EVENT_LBUTTONDOWN:
        # Append the coordinates to the mouse_clicks list
        left_clicks.append((x, y))
        
        # Draw a green circle at the mouse click coordinates
        cv2.circle(image, (x, y), 5, (0, 255, 0), -1)
        
        # Show the updated image with the circle
        cv2.imshow("Image", image)
        
    elif event == cv2.EVENT_RBUTTONDOWN:
        # Append the coordinates to the mouse_clicks list
        right_clicks.append((x, y))
        
        # Draw a red circle at the mouse click coordinates
        cv2.circle(image, (x, y), 5, (0, 0, 255), -1)
        
        # Show the updated image with the circle
        cv2.imshow("Image", image)

# Create a window to display the image
cv2.namedWindow("Image")

# Set the mouse callback function for the window
cv2.setMouseCallback("Image", get_mouse_coordinates)

# Display the image in the window
cv2.imshow("Image", image)

# Wait for a key press to exit
cv2.waitKey(0)

# Destroy the window
cv2.destroyAllWindows()

# Print the list of mouse click coordinates
print(left_clicks)
print(right_clicks)
```

![Peek 2023-05-18 21-37](https://github.com/opengeos/segment-geospatial/assets/5016453/925bc6f0-bd6a-415a-8be7-547de4383701)

**Comment by giswqs** [comment]
Forgot to mention, the workaround would not work for a remote Jupyter instance or Google Colab because it is a pop up window.
