### ISSUE TITLE
Function text_sam_gui() is not defined

### ISSUE THREAD

**Issue by bbscout** [opengeos/segment-geospatial#83]
### Environment Information

-   samgeo version: 0.8.0
-   Python version: 3.10.4
-   Operating System: Windows 10

### Description

In text_sam.py is not defined function `text_sam_gui()`

─────────────────────────────── Traceback (most recent call last) ───────────────╮
│ in <module>                                                                                   
│                                                                                              
│ ❱ 1 sam.show_map()                                                                           
│   2                                                                                            
│                                                                                           
│ c:\Users\MyComputer\.conda\envs\geo\lib\site-packages\samgeo\text_sam.py:419 in show_map    
│                                                                             
│   416 │   │   Returns:                                                        
│   417 │   │   │   leafmap.Map: The map object.                                       
│   418 │   │   """                                                                          
│ ❱ 419 │   │   return text_sam_gui(self, basemap=basemap, out_dir=out_dir, **kwargs)           
│   420                                                                                 
│   421                                                                                          
│   422 def main():                                                                           
╰──────────────────────────────────────────────────────────────────╯
NameError: name 'text_sam_gui' is not defined

### What I Did

```
sam.show_map()
```

**Comment by giswqs** [comment]
Make sure you update the package to the latest version and restart the kernel. 
```bash
pip install -U segment-geospatial
```
