### ISSUE TITLE
can not run segment-geospatial

### ISSUE THREAD

**Issue by wzp8023391** [opengeos/segment-geospatial#84]
### Environment Information

-   samgeo version: 0.8.0
-   Python version: 3.10
-   Operating System: win11

### Description

when I ran sam = LangSAM(), the error appeared, "name 'hf_hub_download is not defined' ", and in the command line, the error seems that the groundingDINO install failed...

### What I Did

```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
```

**Comment by giswqs** [comment]
Try restarting the kernel after install `groundingdino-py`
