### ISSUE TITLE
text_prompts.ipynb fails on Initialize LangSAM class

### ISSUE THREAD

**Issue by p-vdp** [opengeos/segment-geospatial#85]
### Environment Information

-   samgeo version: 0.8.0
-   Python version: 3.9.16
-   Operating System: Windows 11
-   ArcGIS Pro conda env set up using this repo's instructions

### Description

Tried to run through the notebook. At step "Initialize LangSAM class" it throws a NameError on hf_hub_download.

![image](https://github.com/opengeos/segment-geospatial/assets/10510895/6b514dda-4874-4b56-a58e-0c8a96e0baff)

### What I Did

Restarted the kernel and Arc and tried again.  
Installed huggingface_hub in the env via mamba, restarted kernel and tried again.

Looks like there's an issue with importing huggingface_hub in text_sam.py module. Should groundingdino and huggingface_hub be added to requirements.txt etc?

**Comment by giswqs** [comment]
`groundingdino` is not yet available on conda-forge. It can't be added to requirements.txt as the conda-forge package will fail to build if it is included. 

`huggingface_hub` can potentially be added. I will look into it.

**Comment by lukesteinbicker** [comment]
I looked in the package files and found that there is only one class, name "SamGeo". If you write "from samgeo import SamGeo", your issues should be resolved. I assume that there may have been a seperate class named "LangSAM" that was deprecated.

**Comment by giswqs** [comment]
huggingface_hub has been added to requirements.txt. #87 

GroundingDINO and supervision are being added to conda-forge (https://github.com/conda-forge/staged-recipes/pull/22907). It can be added to requirements.txt once they become available on conda-forge.

**Comment by nipunaIdeaforge** [comment]
![Screenshot from 2023-12-04 15-26-54](https://github.com/opengeos/segment-geospatial/assets/143156574/428c069b-6178-4e83-bef9-036655e88f4e)
So how do I import LangSam, I seem to be running into a similar error, "NameError: name 'SLConfig' is not defined"

**Comment by vxi214** [comment]
<img width="805" alt="图片1" src="https://github.com/opengeos/segment-geospatial/assets/67686797/9181a514-7cf9-4be4-b146-10af505cdd09">，Boss, I also encountered this problem, how to solve it?

**Comment by krishnaglodha** [comment]
How is this resolved ?

**Comment by australgisinc** [comment]
This problem keeps appearing

**Comment by geoye** [comment]
Restarting the kernel works for me.

Ref: https://github.com/opengeos/segment-geospatial/discussions/284
