### ISSUE TITLE
It is amazing to see SAM used in remote sensing.I have a few questions and suggestions:

### ISSUE THREAD

**Issue by pythone1** [opengeos/segment-geospatial#89]
1.When using text prompts to varies segment images, DINO doesn't seem to be very friendly to remote sensing images. Even with two very low threshold values, there are still many instances where segmentation fails or is incorrect. Considering the accuracy, are you planning on creating a model specifically tailored for remote sensing images?

2.Regarding the auto segmentation, during the fine segmentation process, even after adjusting the pred_iou_thresh to remove duplicates, there are still a significant number of repeated results in sorted_anns[i]["segmentation"]. At this point, simply converting the masks to vector SHP format will result in the loss of a large number of patches, which is not conducive to subsequent manual modifications. It would be better to preserve all the patches corresponding to each sorted_anns[i]["segmentation"]. This can be achieved by having a geodataframe object corresponding to each sorted_anns[i]["segmentation"], and finally merging and exporting them together.

**Comment by giswqs** [comment]
Thank you for the feedback. 

1. I am new to DINO. I don't know how to fine-tune DINO yet. You are welcome to contribute if you know how to do it. 
2. For now, the algorithm simply adds up all the binary masks together to generate a final binary mask. If some masks have overlaps, they we will be merged as a larger object in the final mask. You will need a raster to generate a vector. I am not sure if it is worthwhile to generate a X number of raster to generate vector data with overlapping polygons, which would have invalid topology.
