### ISSUE TITLE
How to speed up model Inference?

### ISSUE THREAD

**Issue by whuhx** [opengeos/segment-geospatial#95]
### Description

In my experiment, it takes 49 hours to infer an image with a size of 50000×50000. How to speed up?

sam. generate(
    image, mask, batch=True, foreground=True, erosion_kernel=None, mask_multiplier=255
)

**Comment by mishagrol** [comment]
@whuhx hello! Do you utilize CPU or GPU ? 

You may devide your initial image into blocks and run parallel

**Comment by satas12825** [comment]
I have tried to run the model with GPU on docker nothing error but when I monitor the usage of GPU they seem like no one is using GPU, how can I know if my model using GPU to calculate?

**Comment by brendancol** [comment]
@giswqs @satas12825 closing this issue as it lacks a reproducible case and is more than a year old without activity
