### ISSUE TITLE
Qgis problem instalation of SAM

### ISSUE THREAD

**Issue by ANDYAGUIRRE10** [opengeos/segment-geospatial#96]
### Environment Information

-   samgeo version: 0.8.1
-   Python version: 3.11
-   Operating System: windows

### Description

I have installed the "Geometric Attributes" and I have followed the documentation. But this problem appears 
![image](https://github.com/opengeos/segment-geospatial/assets/107130753/cb0d5690-2673-4780-8fde-08ca9f8f0892)
 Then I tried to install it manually but in my windows terminal this was the problem:
![image](https://github.com/opengeos/segment-geospatial/assets/107130753/4fe47e21-4da7-496b-9ea3-29aba0169d15)

### What I Did

I tried to solve this upgrading "pip" in the terminal but the problem persists. So then I tried in pyhton.exe but I think I am not writing correctly the code: 
![image](https://github.com/opengeos/segment-geospatial/assets/107130753/b4e00cb7-25bf-42c1-b961-c5f62252512f)

**Comment by giswqs** [comment]
I have not tested it with QGIS. @BjornNyberg might know more about the installation with QGIS.

**Comment by BjornNyberg** [comment]
Hi @ANDYAGUIRRE10 

This is a windows specific problem for the cython compiler. Make sure that you have updated microsoft visual studio to greater than 14 >. See [here](https://github.com/BjornNyberg/Geometric-Attributes-Toolbox/wiki/FAQ#failed-to-install-segment-geospatial) for more help.

**Comment by ANDYAGUIRRE10** [comment]
> Hi @ANDYAGUIRRE10
> 
> This is a windows specific problem for the cython compiler. Make sure that you have updated microsoft visual studio to greater than 14 >. See [here](https://github.com/BjornNyberg/Geometric-Attributes-Toolbox/wiki/FAQ#failed-to-install-segment-geospatial) for more help.

Hi @BjornNyberg thanks for your help. I will try to update that. Thanks.

**Comment by giswqs** [comment]
I would encourage you open an issue at https://github.com/BjornNyberg/Geometric-Attributes-Toolbox/issues.

**Comment by ANDYAGUIRRE10** [comment]
I will do that. 
Thanks four your help @giswqs
