### ISSUE TITLE
LangSam class downloads checkpoints when already present on filesystem

### ISSUE THREAD

**Issue by frankrowe** [opengeos/segment-geospatial#98]
### Environment Information

-   samgeo version:0.8.1
-   Python version:3.8
-   Operating System:Ubuntu

### Description

I am using the `SamGeo` class as well as the `LangSam` class. The `SamGeo` class requires you to download the checkpoints yourself and initialize using the path, which I am doing. It would be nice if the `LangSam` class could also use the path instead of downloading it's own duplicate of the checkpoints.

Great library!

**Comment by giswqs** [comment]
Yes, yo can specify your own checkout point path, like this:

```python
sam = SamGeo(
    model_type="vit_h",
    checkpoint="/path/to/sam_vit_h_4b8939.pth",  # your own checkpoint full path.
    automatic=False,
    sam_kwargs=None,
)
```

**Comment by frankrowe** [comment]
@giswqs I don't think you can do that for the `LangSAM` class unless I am missing it?

**Comment by giswqs** [comment]
Sorry for missing the `LandSAM` question. I will implement it later today.

**Comment by giswqs** [comment]
What samgeo version did you use? I think the latest version of SamGeo and LangSAM are using the same default cache directory `~/.cache/torch/hub/checkpoints`. You can set `os.environ[''TORCH_HOME"]='/path/to/your/own/checkpoint/dir'` if needed.

```python
CACHE_PATH = os.environ.get(
    "TORCH_HOME", os.path.expanduser("~/.cache/torch/hub/checkpoints")
)
```
SamGeo
https://github.com/opengeos/segment-geospatial/blob/main/samgeo/samgeo.py#L58

LangSAM
https://github.com/opengeos/segment-geospatial/blob/main/samgeo/text_sam.py#L47

**Comment by giswqs** [comment]
Try updating the package using `pip install -U segment-geospatial`. Feel free to reopen if the issue persists.
